"""Case records; keys retain the legacy global catalog order, not record versions.

Metadata is assembled once by registry; keep existing positions stable.
A newly appended record uses the next unused global position.
"""

from __future__ import annotations

from typing import Any

from .flags import PERSON

RECORDS: dict[int, dict[str, Any]] = {
    5: {"id": "portal_promotion_case", "title": "Attributed new-target case reservation", "area": "case", "files": ["portal_promotion.json"],
     "where": "data/clients/<reserved client id>/portal_promotion.json", "format": "JSON object", "version": 1,
     "written_by": "portal.promotion after the complete source portal coordinator, before target restrictions, conflict records or profile enrollment.",
     "versions": [(1, "Exact reciprocal operation plan with target role; attributes new case creation and remains internal after completion. Empty reserved folder or intact exact operation staging can recover; foreign content refuses.")], "exported": True,
     "fields": [("record", "object", "Same fields and immutable plan as portal_promotion, stored with the exact main-store target identity. Q1 removes the own case subtree only after promotion preflight; Q2 excludes this record even if registered as a document.", PERSON)]},
    12: {"id": "source_association", "title": "Canonical source setup and recovery", "area": "case", "files": ["source-association.json"],
     "where": "data/clients/<client id>/source-association.json", "format": "JSON object", "version": 1,
     "written_by": "source_association associate and associated portal engine reconciliation, under the case and portal upload locks. Pending/damaged records hold processing and review before multiwrite publication.",
     "versions": [(1, "Complete byte-preserving portal originals, current named authorization/handover and canonical source publication. Neither document review nor packet approval.")], "exported": True,
     "fields": [("version", "integer", "1.", ""), ("client", "text", "Existing protected main case identity; never enrollment from a remote name.", PERSON),
                ("actor", "text", "Named staff email bound to source setup; future reconciliation rereads its current active account and case access. Explicit authorized handover records a replacement.", PERSON),
                ("destination", "text", "Exact own installation clients/<case>/source path.", PERSON),
                ("files", "array", "Complete retained portal-original identities: exact name, sha256, upload id and actual origin. Portal originals remain in their store; complete copies precede publication.", PERSON),
                ("status", "text", "pending or ready. Pending/damaged setup is a case-wide hold even without document facts; metadata and this record are separate recoverable writes.", ""),
                ("initial", "boolean", "Initial setup refuses unrelated canonical PDFs. Ready named handover verifies known existing nonportal origins before preserving them.", ""),
                ("authorizations", "array", "Chronological named source setup/handover entries (actor email and at). Attribution only; stored roles do not authorize execution.", PERSON)]},
    13: {"id": "staff_upload_receipts", "title": "Staff scan recovery receipts", "area": "case", "files": ["staff-upload-receipts/*.json"],
     "where": "data/clients/<client id>/staff-upload-receipts/<attempt SHA256>.json", "format": "JSON object",
     "written_by": "review.staff_upload_recovery accept; planned file/portal row/job payload precedes commit. Current account, ACL and lifecycle checks apply to retry and worker read.",
     "version": 1, "versions": [(1, "Storage and job-reservation retry identity; reader/audit effects are not globally exactly once. Retained until Q1 case-folder cleanup.")],
     "fields": [("version", "integer", "1.", ""), ("key", "text", "SHA256 of opaque browser attempt, scoped by the protected main case folder.", ""),
                ("client", "text", "Local case id, including an authorized portal-only partial case scaffold.", PERSON),
                ("actor", "text", "Staff email identity at submission; current role/active state/access are reread, never authorized from a stored role.", PERSON),
                ("original", "text", "Original supplied filename, part of immutable retry payload.", PERSON),
                ("source_sha256", "text", "SHA256 of original HTTP bytes before photo conversion.", PERSON),
                ("sha256", "text", "SHA256 of retained validated PDF bytes.", PERSON),
                ("folder", "text", "Source folder association at staging, bound to current configured document/portal roots.", PERSON),
                ("staged", "object", "Immutable worker args: name, pages, by, case (processed at staging), staff_receipt key and optional before source signature/meta_mtime/newest for overnight bookkeeping.", PERSON),
                ("portal_record", "object or null", "One immutable staff upload row when source is portal uploads: id, doc_id, filename, stored, size, sha256, source_sha256, uploaded_at, status, source and by. Retry reconciles by identity/hash, never appends another row.", PERSON),
                ("status", "text", "pending, stored or reserved; means storage/job publication progress, not reader completion or attorney signoff. Missing/pruned job/proof remains unavailable.", "")], "exported": False},
    14: {"id": "facts", "title": "Fact graph", "area": "case", "files": ["fact_graph.json", "fact_graph_raw.json", "fact_graph_reviewed.json"],
     "where": "data/clients/<case id>/fact_graph.json, fact_graph_raw.json, fact_graph_reviewed.json", "format": "JSON object",
     "written_by": "The reader and the overnight run write fact_graph_raw.json (every fact as first read) and fact_graph.json (after the firm's rules); "
                   "refilling a form writes fact_graph_reviewed.json (after staff decisions). src/factgraph/graph.py, src/review/state.py.",
     "version": None, "versions": [(1, "The only shape so far. The file has no version field; the ledger counts it as version 1. Added without "
                                       "raising it (10/03/2026): the fact applicant.name_events, the client's names as a timeline. Added without "
                                       "raising it (10/04/2026): applicant.name_current_typed and applicant.name_birth_typed (the client's own "
                                       "answers about a name change), applicant.name_chosen_given and applicant.name_chosen_family (the name a "
                                       "reviewer typed on the names card), applicant.name_after_marriage_open (present while that card asks) and "
                                       "applicant.name_change_said (present while the client says the name changed or is not sure), and "
                                       "applicant.name_choice_documents (the name-setting documents on the names card when a person chose, "
                                       "from the decision's own record, over).")],
     "fields": [
         ("client_id", "text", "The case's id: the client's folder name. The front desk and the importers make it from the client's name, so it can be a name.", PERSON),
         ("facts", "object", "Every fact, by its key (applicant.date_of_birth); each value is a fact as below.", ""),
         ("facts.applicant.name_events", "object", "The client's names as a timeline (src/name_events.py): a JSON text with each name a document prints "
                                                  "for the client (or the client typed), its date, the document and page; the current name, why, and the "
                                                  "other names used.", PERSON),
         ("facts.<key>.fact_key", "text", "The fact's key again.", ""),
         ("facts.<key>.tier", "integer", "1 read from an official document, 2 derived by a rule, 3 given by a person (the questionnaire or the office).", ""),
         ("facts.<key>.status", "text", "resolved (one value), conflict (documents disagree) or missing.", ""),
         ("facts.<key>.value", "any", "The fact's value as the forms are filled from it.", PERSON),
         ("facts.<key>.sources", "list", "Each document or answer that supports the fact, as below.", ""),
         ("facts.<key>.sources[].doc_id", "text", "Which document (or questionnaire, or reviewer) gave it.", ""),
         ("facts.<key>.sources[].doc_type", "text", "What kind of document that is.", ""),
         ("facts.<key>.sources[].raw_value", "text", "The value exactly as printed or typed.", PERSON),
         ("facts.<key>.sources[].normalized_value", "any", "The same value in the form the product compares (dates as YYYY-MM-DD, names in capitals).", PERSON),
         ("facts.<key>.sources[].confidence", "number", "Reader score from 0 to 1; some readers use fixed constants. It is not a calibrated probability or a substitute for source review.", ""),
         ("facts.<key>.sources[].extracted_at", "text", "When it was read (with its offset).", ""),
         ("facts.<key>.sources[].from_facts", "list", "For a derived value, the fact keys it was worked out from.", ""),
         ("facts.<key>.sources[].instance_id", "text or null", "EV1 stable retained-byte/page-range document instance identity, when this edge came from a retained document.", ""),
         ("facts.<key>.sources[].subject_role", "text or null", "EV2 role printed by the supported reader (holder, birth subject, parent slot, party, etc.), separate from a case-person identity. Unsupported roles stay unmapped.", ""),
         ("facts.<key>.sources[].evidence_version", "text or null", "Digest binding instance/boundary evidence, original page, key, raw/normalized value, reader role and bounded reader/shared-helper code. Full reader/configuration binding is added by EV3.", ""),
         ("facts.<key>.sources[].input_evidence", "list", "Original evidence-version digests supporting a derived source edge; kept alongside the fact-key from_facts dependency.", ""),
         ("facts.<key>.sources[].read_manifest", "object or null", "EV3 read-time declared reader code, normalization assets, package versions and configuration. Null means unrecorded legacy provenance. Upstream OCR/model asset identity remains explicitly unavailable where not pinned; model tags are descriptors, not weight hashes.", ""),
         ("facts.<key>.sources[].reading_issues", "list", "Reasons to check an attempted read, such as competing classifications or a malformed identifier/date; the raw read remains evidence even when no normalized value is proposed.", ""),
         ("facts.<key>.derived_by", "text", "The rule that derived the value, when one did.", ""),
         ("facts.<key>.derived_from", "list", "The fact keys that rule used.", ""),
         ("facts.<key>.resolution", "object", "Set when a rule chose among disagreeing sources: chosen_value, reason, resolved_by, resolved_at.", PERSON),
         ("facts.<key>.missing_reason", "text", "Why a fact is missing, when it is.", ""),
         ("facts.<key>.review", "object", "Set when a person signed the fact off in the review app: chosen_value, reason, resolved_by, resolved_at.", PERSON),
     ], "exported": True},
    15: {"id": "evidence", "title": "Evidence and reading flags", "area": "case", "files": ["evidence.json", "reading_flags.json"],
     "where": "data/clients/<case id>/evidence.json, reading_flags.json", "format": "JSON",
     "written_by": "The reader, when a case is processed (src/review/state.py save_bundle).", "version": None,
     "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("evidence.json", "object", "Where on each document each fact was found: for each document, each question's place on the page.", PERSON),
         ("reading_flags.json", "list", "Places the reader was unsure of: kind (unread, blank_template or unsupported_language), the document and a message.", ""),
     ], "exported": True},
    16: {"id": "meta", "title": "What was read", "area": "case", "files": ["meta.json"], "where": "data/clients/<case id>/meta.json", "format": "JSON object",
     "written_by": "The reader when a case is processed (src/review/state.py save_bundle); a document added later updates it (src/inbox.py).",
     "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("client_id", "text", "The case's id: the client's folder name. The front desk and the importers make it from the client's name, so it can be a name.", PERSON),
         ("source_folder", "text", "The folder the case's documents are read from (the portal's uploads, or a folder of scans): a path the firm chose, which can name the client.", PERSON),
         ("processed_at", "text", "When the case was last processed (with its offset).", ""),
         ("classifications", "object", "For each document (its file name, as the client or the office named it), what kind of document it was taken to be.", PERSON),
         ("errors", "object", "Documents that could not be read, with why.", ""),
         ("derivation", "object", "Which rules and firm policies were applied: rules, policies.", ""),
     ], "exported": True},
    17: {"id": "documents", "title": "Documents", "area": "case", "files": ["documents.json"], "where": "data/clients/<case id>/documents.json",
     "format": "JSON object", "written_by": "The reader when a case is processed (src/documents.py save_run); a person on the Documents tab (set_person, set_quality, "
     "set_language, set_dates, tag, untag); a document added to the case (src/inbox.py, src/review/front_desk.py).",
     "version": 1, "versions": [
         (1, "The first and only version: one record per document, with its type, person, language, dates, identifiers, quality, roles and text. "
             "Since brief G1 (10/03/2026) records also carry person_basis, language_basis, language_country, issued_kind, expires_kind, dates_read, quality_basis, "
             "quality_measures and found; a record written before that is filled in when it is read, so the version was not raised.")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("built", "text", "When the records were last built from a processing run (with its offset).", ""),
         ("documents", "list", "One record per document, as below.", ""),
         ("boundary_plans", "object", "EV1 boundary plans keyed by retained evidence filename. source_sha256 is the full immutable retained-file bytes hash (a converted image PDF is a derivative, not the discarded original photo); fingerprint binds page text and segmenter_version. Each instance has a stable full instance_id, evidence_fingerprint, legacy doc_ids aliases, original first/last zero-based inclusive page range, type, supported/unresolved/reviewed state and reasons. Display pages add one. Matching identifiers and consecutive printed page numbers within the same recognized kind support continuation; distinct identifiers or independent first-page markers split. Bare continuation, translation-certification and footerless Part N phrases keep pages associated but held without corroboration or review. Missing/replaced evidence bytes invalidate the plan. Legacy OCR sources without identity metadata require a fresh reading.", PERSON),
         ("boundary_decisions", "object", "Named human layout decisions per original filename: fingerprint, starts_zero_based, who, role, at, undone and chronological history. Confirmation binds the complete source layout; split/undo reprocess the original, reopening affected field approvals. Saved in this existing case record, included in its export and purge. Boundary review does not establish whose facts these are or confirm extracted values.", PERSON),
         ("boundary_processing", "list", "Original filenames being reprocessed, durably saved before new graph/meta exposure. A crash or failed document-record save leaves a visible hold and excludes their facts until successful reprocessing clears it.", PERSON),
         ("boundary_failure", "object", "A whole-case document processing failure: at and reason. The prior graph/history stays on disk but original-document facts cannot be accepted until a successful full reading clears this marker. Typed human/firm facts are preserved.", ""),
         ("case_subjects", "object", "EV2 version, case_id and people. Each person has a case-scoped opaque id, label, case_role, revision and active state; named changes record who, role, at and history. Names/role labels cannot link identities across cases. This grants no contact, portal, household or case-access authority.", PERSON),
         ("subject_assignments", "object", "EV2 decisions keyed by document instance id: version, fingerprint, retained source_sha256, boundary_evidence_fingerprint, exact evidence_versions, roles mapping each printed slot to subject_id/revision/version, reference_only or reference_edges with note, named who/role/at, undone and chronological history. Unknown, stale, malformed or unsupported subject mappings hold affected facts and packet readiness; current references retain exhibits without supplying values. Corrections invalidate affected field approvals. Catalog ownership is separate and cannot accept a source edge.", PERSON),
         ("documents[].id", "text", "The document's id: the first 16 hex digits of its file's sha256 (a part of a combined scan gets its own).", ""),
         ("documents[].files", "list", "The files that hold it (the same scan uploaded twice is one record with two files): file names the client or the office chose, which can name a person.", PERSON),
         ("documents[].doc_ids", "list", "The names the rest of the product knows it by (the file name, or file.pdf#p3-4 for a part): the same file names.", PERSON),
         ("documents[].pages", "list", "Which pages of the file it covers.", ""),
         ("documents[].type", "text", "What kind of document it is, as an id from the taxonomy (schemas/registers/document_types.json).", ""),
         ("documents[].confidence", "number", "How sure the classifier was, from 0 to 1.", ""),
         ("documents[].person", "text", "Whose it is: applicant, spouse, petitioner, parent, child_1, child_2 ... or unknown.", ""),
         ("documents[].person_basis", "text", "How that was decided: named, identifiers, only_person, set_by_person or unknown.", ""),
         ("documents[].person_set_by", "object", "Who set the person by hand, with their role and the time.", ""),
         ("documents[].person_conflict", "text", "Set when the name on the document and its numbers point to different people.", ""),
         ("documents[].language", "text", "The language it is printed in: en, pt, es, fr, ht or unknown.", ""),
         ("documents[].language_basis", "text", "How that was decided: text, type, country, set_by_person or unknown.", ""),
         ("documents[].language_country", "text", "The country whose language was assumed, when language_basis is country.", ""),
         ("documents[].language_set_by", "object", "Who set the language by hand, with their role and the time.", ""),
         ("documents[].translation_kept", "object", "The answer to \"Keep the translation?\" when a person changed a translated document to English: keep (true or false), the language it was, who and when.", ""),
         ("documents[].issued", "text", "The date it was issued (YYYY-MM-DD), or null.", PERSON),
         ("documents[].expires", "text", "The date it ends (YYYY-MM-DD), or null.", PERSON),
         ("documents[].issued_kind", "text", "What the issued date is: issued, registered, arrived, notice or order.", ""),
         ("documents[].expires_kind", "text", "What the end date is: expires, admit_until or valid_to.", ""),
         ("documents[].dates_read", "boolean", "True when a reader ran on it (so a missing date means none was found on it).", ""),
         ("documents[].dates_set_by", "object", "Who read the dates off the document by hand, with their role and the time.", ""),
         ("documents[].identifiers", "object", "Numbers read from it: a_number, receipt, passport, ssn_last4.", PERSON),
         ("documents[].quality", "text", "How readable the scan is: readable, blurry, cut_off, partial, check or unknown.", ""),
         ("documents[].quality_basis", "text", "How that was decided: measured, reader, retake, set_by_person or unknown.", ""),
         ("documents[].quality_measures", "object", "The numbers behind a measured quality (sharpness, words read, and whether the page has a text layer of its own).", ""),
         ("documents[].quality_set_by", "object", "Who set the quality by hand, with their role and the time.", ""),
         ("documents[].hash", "text", "The file's sha256.", ""),
         ("documents[].source", "text", "Where it came from: portal, scan_inbox, drive, m365, filevine, docketwise, clio or folder.", ""),
         ("documents[].added", "text", "When it was first added (with its offset).", ""),
         ("documents[].added_by", "object", "Who added the scan, and when, when the office added it.", ""),
         ("documents[].roles", "list", "What it can show in a filing (the type's roles).", ""),
         ("documents[].found", "object", "Roles its own text shows beyond its type, each with a plain reason.", ""),
         ("documents[].tags", "list", "Roles a person tagged it with: role, who, role_of_who, at.", ""),
         ("documents[].confidential", "text", "1367 or 208.6 when the law keeps it confidential (8 U.S.C. 1367, 8 CFR 208.6), else null.", ""),
         ("documents[].text", "text", "The text read from the document (empty for a kind that is never read beyond its type).", PERSON),
         ("documents[].translated", "text", "Its English text, when it is in another language and a translation was made.", PERSON),
     ], "exported": True},
    18: {"id": "decisions", "title": "Review decisions", "area": "case", "files": ["decisions.json"], "where": "data/clients/<case id>/decisions.json",
     "format": "JSON object keyed by review item", "written_by": "The review app when a person decides or reopens an item (src/review/state.py record_decision, undo_decision); "
     "a typed answer on a filing's questions is a decision too (src/filing_questions.py).",
     "version": None, "versions": [(1, "The only shape so far; no version field. The history list was added later: an entry written before it counts as its one decision.")],
     "fields": [
         ("<item id>", "object", "One review item's entry: the latest decision's fields at the top, the whole chain under history.", ""),
         ("<item id>.action", "text", "confirm, set (corrected), blank (left blank), acknowledge, or absent (the client has no such paper: item id absent:<paper>).", ""),
         ("<item id>.absence", "object", "For absent: paper (passport, visa, i94, birth_certificate, marriage_certificate, divorce_decree or court_order), reason (never_had, lost, cannot_obtain, expired or office_later) and line (the few words the person added).", PERSON),
           ("<item id>.values", "object", "For set: the fact keys and the values the person entered.", PERSON),
           ("<item id>.evidence_confirmation", "object", "EV3 manual retained-source review: version, basis, model_release_approval=false, and per-key chosen value, fingerprint and proof. Binds retained bytes/page range, original raw/normalized edges, boundary and subject versions, quality, read-time and current expected configuration, inventory digest and input decisions. Invalid or stale proofs do not count; history retains their record. This is not legal or model-release approval.", PERSON),
         ("<item id>.reviewer", "text", "Who decided.", ""),
         ("<item id>.role", "text", "Their role, when staff accounts are on.", ""),
         ("<item id>.old", "text", "The text a decision replaced (a paragraph of a declaration).", PERSON),
         ("<item id>.over", "list", "For \"Which name is current?\": the name-setting documents (file names) on the card when the person chose; "
                                    "one that arrives later reopens the card (added 10/04/2026 without raising the version).", PERSON),
         ("<item id>.name_evidence", "text or null", "For a names Save: SHA256 snapshot of the current applicant marriage reads, including original raw and normalized values, source instance and evidence identities, read-time configuration, party, page and unsuccessful read state. It detects changed reads at the same filename; it grants no subject, source or legal approval. A missing legacy snapshot or changed current snapshot requires a new names review when marriage evidence is present; prior choices and Undo history remain on file.", PERSON),
         ("<item id>.note", "text", "The person's note, which a blocking item requires.", PERSON),
         ("<item id>.at", "text", "When (with its offset).", ""),
         ("<item id>.item", "object", "The item decided: id, kind, level, title, group and the fact keys it was about.", ""),
         ("<item id>.undone", "object", "Set when the decision was reopened: by, role, at, and why when the product itself ended it (the paper the office marked absent arrived and was read).", ""),
         ("<item id>.history", "list", "Every decision ever made on the item, oldest first, each with the fields above (without item or history).", PERSON),
     ], "exported": True},
    19: {"id": "case_path", "title": "The case's own path", "area": "case", "files": ["path.json"], "where": "data/clients/<case id>/path.json", "format": "JSON object",
     "written_by": "The review app, the Path tab (src/path.py): only once a change to the template's path is saved. A paralegal's change waits as proposed; an attorney approves it.",
     "version": 1, "versions": [(1, "The first shape: approved, proposed, history.")],
     "fields": [
         ("version", "number", "The shape's version (1).", ""),
         ("approved", "object", "The path every derived thing uses (documents, questionnaire, deadlines, packet order, the client's page); null: the template's.", ""),
         ("approved.steps", "list", "The steps in order: each {id, date}. An id is a stage the templates hold (schemas/registers/journey.json); date: the expected date, or null.", ""),
         ("approved.removed", "list", "The filings the case leaves out (ids the templates name, ead for the I-765 ...).", ""),
         ("approved.by, at, role, reason, change", "text", "Who changed it, when, their role, why (required), and the change in words.", ""),
         ("approved.approved_by, approved_at", "text", "The attorney who approved it, and when.", ""),
         ("proposed", "object", "A change waiting for an attorney, the same shape as approved without the approval; null when none waits. It derives nothing.", ""),
         ("history", "list", "Every proposal, approval, refusal and return to the template: at, by, action, change, reason.", ""),
     ], "exported": True},
    20: {"id": "journey", "title": "Where the case stands (status.json and the journey files)", "area": "case", "files": ["status.json"],
     "where": "data/clients/<case id>/status.json", "format": "JSON object",
     "written_by": "The review app: marks on the case timeline (src/journey.py mark), a filing recorded as mailed (src/prefile.py), the filed mark (src/review/overview.py). "
                   "The timeline itself is worked out from this and the other records every time (journey_summary.json is only its cache).",
     "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("filings", "list", "Each filing recorded as mailed or filed online, oldest first (the filings fields below).", ""),
         ("filings[].filing", "text", "Which filing, as an id (i485, i601a ...).", ""),
         ("filings[].variant", "text", "Which variant of the packet was built.", ""),
         ("filings[].title", "text", "The filing's name as the packet gives it.", ""),
         ("filings[].forms", "list", "The main forms in the package (I-601, I-212 ...), which the client's page names.", ""),
         ("filings[].mailed_on", "text", "The date it was mailed or filed (YYYY-MM-DD).", ""),
         ("filings[].carrier", "text", "How: a carrier's name, Hand delivery or Online.", ""),
         ("filings[].tracking", "text", "The carrier's tracking number, or the online confirmation number.", PERSON),
         ("filings[].mail_to", "text", "Where it was sent.", ""),
         ("filings[].fee", "text", "The fee the packet stated.", ""),
         ("filings[].packet_sha256", "text", "The sha256 of the packet that was mailed.", ""),
         ("filings[].built_at", "text", "When that packet was built (with its offset).", ""),
         ("filings[].override", "text", "The attorney's reason for mailing despite a failed check.", PERSON),
         ("filings[].failed_checks", "list", "The checks that failed.", ""),
         ("filings[].online", "boolean", "True for a filing made in the USCIS online account.", ""),
         ("filings[].receipt", "text", "The receipt number, once USCIS shows it.", PERSON),
         ("filings[].receipt_by", "text", "Who added the receipt number.", ""),
         ("filings[].receipt_at", "text", "When it was added (with its offset).", ""),
         ("filings[].bundle_sha256", "text", "The sha256 of the online-filing files.", ""),
         ("filings[].by", "text", "Who recorded it.", ""),
         ("filings[].at", "text", "When it was recorded (with its offset).", ""),
         ("filed_at", "text", "When the case was marked filed (with its offset).", ""),
         ("filed_by", "text", "Who marked it filed.", ""),
         ("removed_filings", "list", "Filing records an attorney took away, each with removed_by and removed_at.", ""),
         ("journey", "object", "What people marked on the timeline, as below.", ""),
         ("journey.done", "object", "Steps marked done, by the step's id: by, at, note.", PERSON),
         ("journey.stage", "object", "A stage a person set: value, by, at, and a free-text note.", PERSON),
         ("journey.track", "object", "A track a person set (sij, family, naturalization, asylum, caa, vawa, t_visa, u_visa, daca): value, by, at, and a free-text note.", PERSON),
         ("journey.lpr_date", "object", "The date the client became a permanent resident: value, by, at, note.", PERSON),
         ("journey.ours", "object", "Set when the firm filed the case itself: by, at.", ""),
         ("journey.hearings", "list", "Court hearings: id, date, time, kind, court, judge, detained, by, at, note, source, confirmed, result.", PERSON),
         ("journey.bring", "object", "A person's answer about the list of what to bring that the reader took from an appointment notice, by the notice's id: state (confirmed or rejected), lines "
                                      "(the list they looked at), by, at. Until confirmed the list reaches no client.", PERSON),
         ("journey.places", "object", "A person's answer about an appointment's address, by the notice's id: state (confirmed or rejected), read (what the reader took), typed (an address a "
                                       "person typed instead), by, at. A reminder names the place only once it is confirmed or typed.", PERSON),
         ("journey.oath", "object", "The oath ceremony: date, time, place, by, at.", PERSON),
         ("journey.moves", "list", "Moves the client reported: id, date, address, by, at.", PERSON),
         ("journey.people", "list", "People on the case who are not clients: id, given_name, family_name, name, relationship, phone, email, person, by, at.", PERSON),
         ("journey.linked", "list", "Family members' cases linked to this one: client, relationship, by, at, own_instance and peer instance, origin case and operation. Current both-case authority and immutable pair incarnations are required; a link never transfers access, consent or legal authority. Exposed readers filter current target permission and unresolved operations.", PERSON),
         ("journey.family_instance", "text", "Opaque 32hex own case incarnation created only during explicit authorized linking; binds links and recovery against same-ID recreation. Not a bearer credential.", PERSON),
         ("journey.family_pending", "object", "Optional reciprocal operation denial: source case, exact operation and own instance. Partial relationship effects remain hidden pending current both-case authorized recovery.", PERSON),
         ("journey.family_operations", "list", "Retained exact reciprocal link/unlink plans: id, source/target case, source_instance/target_instance, action, relationship, by, at, pending/completed state and audit source/target ledger hashes. Current both-case authority and exact identities are required before recovery effects; Q2 excludes internal status while firm export retains it.", PERSON),
     ], "exported": True},
    21: {"id": "access", "title": "Who may open the case", "area": "case", "files": ["access.json"], "where": "data/clients/<case id>/access.json", "format": "JSON object",
     "written_by": "The review app when an attorney restricts a case, names staff on it or switches automatic messages (src/restricted.py); a new client of a protected kind "
                   "from the front desk or an import (protect_new).",
     "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("marked", "object", "The attorney's mark: on, by, at, reason and, for a protected kind of case, law.", PERSON),
         ("people", "list", "Staff named on the case: email, name, by, at.", ""),
         ("messages", "object", "Automatic messages to the client: on, by, at, reason.", PERSON),
         ("history", "list", "Every change: at, by, what and, where one was given, reason.", PERSON),
     ], "exported": True},
    22: {"id": "deadlines_set", "title": "Deadlines a person set, and who is responsible for a deadline", "area": "case", "files": ["deadlines_set.json"],
     "where": "data/clients/<case id>/deadlines_set.json", "format": "JSON object",
     "written_by": "The review app, from the case page: Add a deadline, naming the person responsible, marking one done (src/deadlines_set.py). Never deleted from: a deadline marked done "
                   "is hidden from the lists and kept here.",
     "version": 1, "versions": [(1, "The first and only version: the deadlines a person set, and the assignments of the product's own deadlines to a person.")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("deadlines", "list", "Each deadline a person set, oldest first, as below.", ""),
         ("deadlines[].id", "text", "The deadline's id: set.1, set.2 and so on, counting up and never used again.", ""),
         ("deadlines[].title", "text", "What the deadline is for, as the person typed it.", PERSON),
         ("deadlines[].date", "text", "The day it falls (YYYY-MM-DD).", PERSON),
         ("deadlines[].who", "text", "The staff member responsible: their sign-in email, or null for nobody yet.", PERSON),
         ("deadlines[].who_name", "text", "Their name (or, without staff accounts, the name that was typed).", PERSON),
         ("deadlines[].role", "text", "Their role when they were named (attorney or paralegal): who the deadline is on the list of when it has no one named.", ""),
         ("deadlines[].note", "text", "The person's note, or null.", PERSON),
         ("deadlines[].by", "text", "Who set the deadline.", ""),
         ("deadlines[].at", "text", "When it was set (with its offset).", ""),
         ("deadlines[].done", "object", "Set when it was marked done: by (who) and at (when). A deadline marked done is hidden from the lists and kept.", ""),
         ("deadlines[].task", "boolean", "True when the row is one of the case's tasks (src/case_notes.py): the same row, so every list of deadlines shows it.", ""),
         ("deadlines[].carried_from", "text", "For a task that came over from a prospect that became a client: the prospect's id and the task's id there, with a bar between them.", PERSON),
         ("assigned", "object", "The person responsible for a deadline the product worked out, by that deadline's id. The deadline itself is never changed.", ""),
         ("assigned.<deadline id>.email", "text", "The staff member's sign-in email, or null.", PERSON),
         ("assigned.<deadline id>.name", "text", "Their name.", PERSON),
         ("assigned.<deadline id>.by", "text", "Who named them.", ""),
         ("assigned.<deadline id>.at", "text", "When (with its offset).", ""),
     ], "exported": True},
    23: {"id": "case_notes", "title": "Case notes", "area": "case", "files": ["notes.json"], "where": "data/clients/<case id>/notes.json", "format": "JSON object",
     "written_by": "The review app, from the case page: a note, or a correction of an earlier note (src/case_notes.py). Never edited and never deleted: a correction is a new note. "
                   "A prospect's notes come over when it becomes a client.",
     "version": 1, "versions": [(1, "The first and only version (brief I4, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("notes", "list", "Each note, oldest first, as below.", ""),
         ("notes[].id", "text", "The note's id: n.1, n.2 and so on, counting up and never used again.", ""),
         ("notes[].text", "text", "What the person wrote, as they wrote it (the spaces tidied).", PERSON),
         ("notes[].by", "text", "Who wrote it.", ""),
         ("notes[].role", "text", "Their role (attorney or paralegal), or null.", ""),
         ("notes[].at", "text", "When it was written (with its offset): for a note carried over from a prospect, when it was written there.", ""),
         ("notes[].corrects", "text", "The id of the earlier note this one corrects, or null. The earlier note is left as it was.", ""),
         ("notes[].carried", "text", "For a note that came over from a prospect that became a client: the prospect's id.", PERSON),
         ("notes[].attorney_only", "boolean", "True on a note an attorney marked for attorneys only (the case page and Find across the firm show it to attorneys only); absent otherwise.", ""),
     ], "exported": True},
    24: {"id": "purge_steps", "title": "The two steps before a purge", "area": "case", "files": ["purge.json"], "where": "data/clients/<case id>/purge.json", "format": "JSON object",
     "written_by": "An attorney on the case's Agreement and closing tab (src/purge.py record_contact, review_originals). It goes with the case when the case is purged.",
     "version": 1, "versions": [(1, "The first and only version (brief Q1, 10/05/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("contact", "list", "Each attempt to reach the client about their file: how (phone, letter, email, portal, in_person), on (the day, YYYY-MM-DD), note, by, role, at.", PERSON),
         ("originals", "object", "The review of the originals the office holds: none_held, items (doc, kind, choice: none, returned or kept; where it is stored), by, role, at.", ""),
     ], "exported": True},
    25: {"id": "apply_for", "title": "What could this person apply for: the answers", "area": "case", "files": ["apply_for.json"], "where": "data/clients/<case id>/apply_for.json",
     "format": "JSON object",
     "written_by": "The review app, from the case page or the prospect's page: a person answers a question yes, no or unsure (src/apply_for.py). The questions are the product's "
                   "(schemas/registers/apply_for.json); this file holds only the answers. A prospect's answers come over when it becomes a client.",
     "version": 1, "versions": [(1, "The first and only version (brief I4, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("answers", "object", "The answers, by the question's id.", ""),
         ("answers.<question id>.answer", "text", "The latest answer: yes, no or unsure, or null when it was taken back.", PERSON),
         ("answers.<question id>.by", "text", "Who gave the latest answer.", ""),
         ("answers.<question id>.role", "text", "Their role (attorney or paralegal), or null.", ""),
         ("answers.<question id>.at", "text", "When it was given (with its offset).", ""),
         ("answers.<question id>.history", "list", "Every answer ever given to the question, oldest first: answer, by, role, at. An answer changed is a new entry.", PERSON),
     ], "exported": True},
    26: {"id": "g28_choices", "title": "The G-28's choices for the case", "area": "case", "files": ["g28_choices.json"], "where": "data/clients/<case id>/g28_choices.json",
     "format": "JSON object",
     "written_by": "The review app, from the case's G-28 card: a person confirms the card, changes one choice with a reason, or takes the last change back (src/g28.py). "
                   "Nothing is deleted: a change is kept in the history with the record as it was before it.",
     "version": 1, "versions": [(1, "The first and only version (brief K4, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("choices", "object", "What a person changed from the office's setting on this case, by item: mail (the client's mailing address on the G-28), 1a, 1b, 1c "
                               "(Part 4's items) and others (the mailing address on the I-485 and the I-765). An item not here follows the office's setting.", ""),
         ("choices.<item>.value", "text", "The choice: for mail office, physical or mailing; for 1a, 1b and 1c true or false; for others office or client.", ""),
         ("choices.<item>.reason", "text", "Why this case differs from the office's setting, in the person's words.", PERSON),
         ("choices.<item>.by", "text", "Who changed it.", ""),
         ("choices.<item>.role", "text", "Their role (attorney or paralegal), or null.", ""),
         ("choices.<item>.at", "text", "When (with its offset).", ""),
         ("confirmed", "object", "The card as a person confirmed it, or null: by, role, at, and values (the choices as they stood). The card counts as confirmed only while "
                                 "the values it shows now are these.", ""),
         ("history", "list", "Every confirmation, change, return to the office's setting and undo, oldest first: n, at, by, role, action, item, before (choices and "
                             "confirmed as they were before it), undone (who took it back and when, or null).", PERSON),
     ], "exported": True},
    27: {"id": "rebuild", "title": "Rebuilding the forms after a release", "area": "case", "files": ["rebuild.json", "rebuild_previous/*"], "where": "data/clients/<case id>/rebuild.json, rebuild_previous/",
     "format": "JSON, PDF",
     "written_by": "The review app, from the case's \"Rebuild the forms\" card, when a person rebuilds the forms with a new release, confirms the boxes that changed or keeps the "
                   "previous forms (src/rebuild.py). Nothing is deleted: each rebuild, confirmation and return to the previous forms stays in the history. rebuild_previous/ holds the "
                   "case's forms, packet, facts and rule list as they were before a rebuild (named <filing>.<file>, with <filing>.index.json listing them), until the rebuild is "
                   "confirmed or put back; then the copies are dropped.",
     "version": 1, "versions": [(1, "The first and only version (brief K5, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("rules_added", "list", "The rules a rebuild brought the case: filing, to_version and rules (their ids), so a second filing's rebuild still says which were new.", ""),
         ("filings", "object", "One entry for each filing that was rebuilt, by the filing's id.", ""),
         ("rebuild_previous/*", "file", "The files a rebuild changed, as they were before it: facts, rule list, flag report, forms, packet and its record.", PERSON),
         ("filings.<filing>.pending", "object", "The last rebuild, or null: at, by, role, from_version, to_version, changes (each changed box: form, box, key, old, new, why, reason; null while the "
                                                "rebuild is running) and confirmed (by, role, at, or null while a person has not confirmed it). The packet is a draft until it is confirmed.", PERSON),
         ("filings.<filing>.history", "list", "Every rebuild, confirmation and return to the previous forms, oldest first: at, by, role, action (rebuilt, confirmed or kept_previous), from_version, to_version, changed (how many boxes).", ""),
     ], "exported": True},
    29: {"id": "conflicts", "title": "The conflict check", "area": "case", "files": ["conflict_check.json"], "where": "data/clients/<case id>/conflict_check.json",
     "format": "JSON object",
     "written_by": "The front desk when a client is added, the Docketwise import, the command line's import and the Clio sync when a case comes in (as not yet decided), and an attorney deciding "
                   "on the screen (src/conflicts.py). Written before anything else of a new case.",
     "version": 1, "versions": [(1, "The first shape: subject, parties, searches, decision, history.")],
     "fields": [
         ("version", "integer", "The record's version (1).", ""),
         ("subject", "object", "The client as the search looked for them: name, other_names, dob (YYYY-MM-DD), a_number, passport.", PERSON),
         ("parties", "list", "The other side the intake named: name, dob, role (adverse, abuser, trafficker, petitioner, spouse, parent or other).", PERSON),
         ("searches", "list", "Each search made for the case: id (its row in the conflict log), at, by, purpose (add, import, sync, cli: the command line's import, case), hits, strong, adverse (counts).", ""),
         ("decision", "object", "What was decided, now: decision (none, declined, waived or undecided), words, reason, by, role, at, search.", PERSON),
         ("history", "list", "Every decision, oldest first, in the same shape.", PERSON),
         ("abandoned", "object", "Set when an add stopped before the client was made and no client took the record up within an hour: at, why. The case is then out of the people index and the lists.", ""),
         ("resumed", "list", "When an abandoned record was taken up again by an add of the same name (the times, with their offset).", ""),
     ], "exported": True},
    30: {"id": "office", "title": "The case's other records", "area": "case",
     "files": ["office.json", "translations.json", "declarations.json", "companions.json", "packet.json", "packet_*.json", "online_filing.json", "online_bundle_*.json",
               "case_status.json", "rfe/*.json"],
     "where": "data/clients/<case id>/office.json, translations.json, declarations.json, companions.json, packet*.json, online_filing.json, online_bundle_*.json, "
              "case_status.json, rfe/",
     "format": "JSON", "written_by": "The review app and the overnight run (src/offices.py, src/translation.py, src/drafting.py, src/packet.py, src/online_filing.py, "
     "src/case_status.py, src/rfe.py).", "version": None, "versions": [(1, "The only shape so far; translations.json carries a version field of 1.")],
     "fields": [
         ("office.json", "object", "The office a person chose for the case: office, by, at.", ""),
         ("translations.json", "object", "Each foreign-language document's translation state: who made it, the translator, the signature, the text.", PERSON),
         ("declarations.json", "object", "The client's declaration as drafted from their own answers, each paragraph with who accepted or edited it.", PERSON),
         ("companions.json", "object", "Which companion forms were filled and when.", ""),
         ("packet.json, packet_<filing>.json", "object", "A packet's contents list: forms, exhibits, checklist, page ranges, signatures, who built it and when, the release that built it (version), and what the G-28 was filled with (g28).", PERSON),
         ("packet_choices.json, packet_choices_<filing>.json", "object", "Where staff moved documents in the packet: files, and a log of who moved what and when.", ""),
         ("online_filing.json", "object", "Paper or online for each filing: mode, by, at, and a log.", ""),
         ("online_bundle_<filing>.json", "object", "The online-filing files' list: what was built, by whom, their sha256.", ""),
         ("case_status.json", "object", "USCIS's case status answers for the case's receipts, saved by the nightly check.", PERSON),
         ("rfe/<key>.json, rfe/<key>_manifest.json", "object", "A response to a USCIS request: the items, the address, the due date, and the built response's list.", PERSON),
     ], "exported": True},
    31: {"id": "client_file_policy", "title": "Attorney-selected client-file policy", "area": "case",
     "files": ["client_file_policy.json"], "where": "data/clients/<case id>/client_file_policy.json", "format": "JSON object",
     "written_by": "Explicit currently authorized attorney determinations (src/client_file_policy.py). No client-residence inference, delivery, billing or automatic deletion.",
     "version": 1, "versions": [(1, "Jurisdiction, protective handover and separate retention/destruction authority; optional inventory approval upgrade. Expanded canonical case-evidence presence/byte bindings require renewed review of earlier snapshots without overwriting history.")],
     "fields": [
         ("version, case, identity", "integer, text, digest", "Version, own case ID and original enrollment or existing case-person incarnation binding. A recreated case cannot reuse this policy.", ""),
         ("revision, facts_revision", "integer", "Monotonic record and semantic-facts versions. Every mutation requires the current record revision.", ""),
         ("facts", "object", "Explicit profile selection, attorney admissions, principal office, tribunal/predominant effect, choice-of-law basis and rationale; matter type; age at representation completion, completion/majority dates, special milestones, preservation holds, originals and other requirements. Unknown legal facts remain unknown; operational closure supplies no legal completion date.", PERSON),
         ("applicability_approval", "object or null", "Attorney actor/role/time, facts revision, current case/facts/office/lifecycle and exact canonical documents/fact-graph presence/byte digest and profile ID/version/source-content digest; actual official-source review. Enables only the policy prerequisite for protective handover.", ""),
         ("retention_approval", "object or null", "Separate current attorney approval with the same binding, explicit inclusive keeping date and determination; destruction is held through that whole day. Supported conservative minimum is rechecked; special or unresolved protections remain held.", ""),
         ("destruction_approval", "object or null", "Separate current attorney approval, exact retention-approval digest, resolved-protection review and determination. Never replaces purge waiting, second-attorney or race safeguards.", ""),
         ("inventory_approval", "object or null", "Optional version-1 upgrade: attorney actor/role/time, current policy snapshot and exact inventory digest including private own source-folder metadata/root generation; complete per-file path, output/input SHA256, include boolean and reason. Required cover cannot be excluded; unsupported material requires a client-safe alternative. Original raw notes stay internal; only a reviewed own-case text rendering is eligible. Legacy absence requires review and retains previous policy/history.", PERSON),
         ("recipient", "object or null", "Current attorney-reviewed recipient name, client/authorized representative/successor counsel authority, supporting authority evidence, in-person/mail/secure-transfer/email method and destination. Not proof of delivery and no provider send.", PERSON),
         ("history", "list", "Every explicit facts, applicability, inventory, retention, destruction or recipient determination with sequential revision, actor/role/time and exact retained detail. Superseded approvals remain historical.", PERSON),
     ], "exported": True},
    32: {"id": "engagement", "title": "The agreement, its letters and the case's end", "area": "case", "files": ["engagement.json", "engagement/*.pdf", "engagement/signed-*.json"],
     "where": "data/clients/<case id>/engagement.json, engagement/", "format": "JSON object, PDF",
     "written_by": "The review app's Agreement and closing tab: the agreement made, sent to the portal, signed on paper and counter-signed; the case declined, "
                   "withdrawn, transferred, closed or reopened; the client's file made and handed over; a destruction recorded (src/engagement.py). The client's "
                   "signature in the portal is copied in from the portal's own record (engagement.sync).",
     "version": 1, "versions": [(1, "The first and only version (brief I1, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("letters", "list", "Every letter made for the case, oldest first, as below.", ""),
         ("letters[].id", "text", "The letter's id on the case (L1, L2 ...).", ""),
         ("letters[].kind", "text", "engagement (the agreement), non_engagement, disengagement or closing.", ""),
         ("letters[].office", "text", "The office whose wording it was made from (main, office_2 ...).", ""),
         ("letters[].office_name", "text", "That office's name.", ""),
         ("letters[].template_version", "integer", "The version of the office's wording it was made from (0: as shipped).", ""),
         ("letters[].english_version", "integer", "The version at which that wording's English last changed.", ""),
         ("letters[].language", "text", "The client's language (en, pt, es, ht).", ""),
         ("letters[].translation", "text", "machine or firm, when the letter carries the client's language too; else null.", ""),
         ("letters[].titles", "object", "The letter's title in each language it carries.", ""),
         ("letters[].texts", "object", "The letter's paragraphs as made, in English and in the client's language: the client's name, the filings, the dates and what the office typed are in them.", PERSON),
         ("letters[].client", "text", "The client's name as the letter gives it.", PERSON),
         ("letters[].letterhead", "object", "The letterhead it was made with: the firm's name, tagline, address and attorneys.", ""),
         ("letters[].signer", "object", "Who signs it for the firm: the name and the lines under it.", ""),
         ("letters[].date", "text", "The letter's date (YYYY-MM-DD).", ""),
         ("letters[].filings", "list", "The filings it is about, as ids (i485, i360 ...).", ""),
         ("letters[].fee", "text", "The fee as the office typed it (an agreement only; the product never fills one in).", PERSON),
         ("letters[].government_fees", "text", "The government's fees as the office typed them, or none (the letter then says they will be told).", ""),
         ("letters[].additions", "text", "The attorney's own additions to the letter.", PERSON),
         ("letters[].matter", "text", "What the person asked about, as the attorney typed it (a non-engagement letter).", PERSON),
         ("letters[].returned", "text", "What the firm returns, as the attorney typed it (a disengagement letter).", PERSON),
         ("letters[].how", "text", "How to get the file, as the attorney typed it (a closing letter).", PERSON),
         ("letters[].deadlines", "list", "The deadlines the letter listed: date and what (a disengagement letter).", PERSON),
         ("letters[].made_by", "text", "Who made it.", ""),
         ("letters[].made_role", "text", "Their role.", ""),
         ("letters[].made_at", "text", "When (with its offset).", ""),
         ("letters[].approved", "boolean", "True when the attorney had approved the letters' wording when it was made or sent (it then carries no DRAFT mark).", ""),
         ("letters[].wording_hash", "text", "The sha256 of the office's wording it was made from, every language: it is sent or signed only while that wording is the approved one.", ""),
         ("letters[].sent", "object", "When the agreement was put on the client's portal to sign: by, at, and delivery (what the \"there's news\" message did, in words).", ""),
         ("letters[].signature", "object", "The client's signature: how (portal or paper); in the portal the typed name, at, the internet address the request came from and the "
                                          "language shown, accepted consent and authenticated portal client; on paper the date signed (on), the scan's file name and sha256, and who recorded it (by, at).", PERSON),
         ("letters[].countersignature", "object", "The attorney's counter-signature: the typed name, by (the signed-in person), role, at.", ""),
         ("end", "object", "The case's end, or null while it is open: state (declined, withdrawn, transferred, closed), on (YYYY-MM-DD), reason, ended_by (firm or client), "
                           "by, role, at and letter (its id). Operational closure is not a legal representation-completion determination; the office clock is planning only until current case-policy approval. "
                           "a record written before 10/03/2026's fix may also hold retention, which nothing reads.", PERSON),
         ("history", "list", "Earlier ends, each with reopened: by, role, at, reason.", PERSON),
         ("file", "object", "Client handover preparation: name, files, bytes, sha256, by, at, included manifest, reasoned exclusions and warnings (attorney only); language and draft cover. New preparation has no inferred jurisdiction default. Current policy, inventory and recipient reviews bind the archive; legacy preparation requires renewed review.", PERSON),
         ("file.binding, file.binding_sha256, file.policy", "object, digest, object", "Exact current policy snapshot, inventory digest, inventory-approval digest and recipient-approval digest; binding SHA256 and retained applicability approval source/version. Changed bytes, evidence, recipient or policy invalidate preparation, approval, download and receipt claims; historical records remain.", PERSON),
         ("file.approved", "object or null", "Named attorney/role/time approval of this exact archive SHA256 and binding digest after cover, included/excluded material and recipient review; no delivery claim.", ""),
         ("file.returned", "object or null", "Actual manually recorded delivery: archive and binding SHA256, current recipient digest and retained authority/method, actual day and acknowledgement reference, recorder/role/time. Day cannot precede current archive approval or be future. No provider send or automatic receipt; stale later bindings do not erase the historical receipt.", PERSON),
         ("file_history", "list", "Earlier preparation, approval and handover metadata and fingerprints, retained when the single staging archive is replaced; no extra archive copy.", PERSON),
         ("electronic_consent", "object", "Case language consent wording approved explicitly by an attorney: text, language, by, at, certified translator and text sha256; absent by default.", PERSON),
         ("letters[].signing_evidence", "object", "R2 references for immutable portal signature: PDF and record sha256, own ledger hash and time. Live verification requires a valid covering daily anchor.", PERSON),
         ("letters[].consent", "object", "The approved electronic-signature consent copied into the exact letter shown to the client; absent or null when not approved.", PERSON),
         ("engagement/signed-*.json", "file", "Canonical exact shown letter and server-recorded signing evidence; evidence sidecar references the R2 commitment row. Written once and never reconstructed.", PERSON),
         ("engagement/signed-*.pdf", "file", "Immutable signed letter before later countersigning; given with live certificate after R2 anchor verification.", PERSON),
         ("destroyed", "object", "Set only with current case-specific legal destruction authority after its inclusive keeping date and operational closure: by, role, at, folder_removed, export_kept, note and policy_authority; no elapsed planning-clock authority.", ""),
         ("engagement/<kind>-<id>.pdf", "file", "Each letter as made, with the letterhead and, for the agreement, the signatures; DRAFT until the attorney approves the wording.", PERSON),
         ("engagement/agreement-<id>-signed-on-paper.pdf", "file", "The scan of an agreement the client signed on paper.", PERSON),
     ], "exported": True},
    33: {"id": "eoir26a", "title": "The fee waiver request (Form EOIR-26A)", "area": "case", "files": ["eoir26a.json", "eoir26a/*"],
     "where": "data/clients/<case id>/eoir26a.json, eoir26a/", "format": "JSON object, PNG, PDF",
     "written_by": "The review app's Fee waiver tab: the questions put on the client's page, item 4 edited and approved, the signing opened on the client's page, the paper "
                   "signature recorded, the attorney's attestation, a signature voided (src/eoir26a.py). The client's opening and signing in the portal are copied in from the "
                   "portal's own record (eoir26a.sync). The figures themselves are the client's portal answers, or review decisions a staff member typed; item 4's approved "
                   "sentence is a review decision too (decisions.json).",
     "version": 1, "versions": [(1, "The first and only version (brief L4, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("request", "object", "The case's one request, or null: as below.", ""),
         ("request.id", "text", "The request's id on the case (F1, F2 ...).", ""),
         ("request.kind", "text", "Why it was made: motion or appeal (the attorney asked for the fee to be waived there) or by_hand.", ""),
         ("request.made_by", "text", "Who made it.", ""),
         ("request.made_role", "text", "Their role.", ""),
         ("request.made_at", "text", "When (with its offset).", ""),
         ("request.sent", "object", "When the questions were put on the client's page: by, at, and delivery (what the \"there's news\" message did, in words); null when the office typed the figures.", ""),
         ("request.opened", "object", "When the attorney opened the signing on the client's page: by, role, at, drawn (a drawn signature was allowed) and delivery.", ""),
         ("request.viewed", "text", "When the client first opened the request on their page (with its offset), copied from the portal.", ""),
         ("request.sentence", "object", "Item 4's approval: state (approved or blank), by, role, at, wording (the shipped wording it is, when unchanged), slots (the amounts filled in), edited and over (the nine amounts it was approved beside: item 4 is approved again when they change). The approved text is the review decision eoir26a:hardship.", ""),
         ("request.sentence_draft", "object", "The paralegal's edit of item 4 waiting for the attorney: text, by, role, at.", PERSON),
         ("request.signature", "object", "The client's signature: how (portal or paper); in the portal the typed name, case_name (the client's legal name the case held when the signing was opened: the typed name equals it, and it is what the form prints), at, the internet address the request came from, the language shown and drawn "
                                         "(the image's file name and sha256); on paper the date signed (on), the scan's file name and sha256, and who recorded it (by, role, at); and covers: the nine amounts "
                                         "(figures, by line) and item 4's sentence that the signature was made over.", PERSON),
         ("request.name_refused", "list", "Each time the client typed a name that is not the one the case holds: at (with its offset). The name typed is not kept. Copied from the portal; the Fee waiver tab says it to staff.", ""),
         ("request.attestation", "object", "The attorney's attestation: typed_name, by, role, at, eoir_id and printed_name (the office's, from Settings), covers (as the signature's) and, for a form signed on paper, paper_page_2 (the attorney's confirmation that page 2 of the paper was signed and dated: confirmed, at).", PERSON),
         ("history", "list", "Earlier requests, each as above with voided: by, role, at and why.", PERSON),
         ("eoir26a/signature-<id>-<code>.png", "file", "The signature the client drew on their phone, as the portal kept it (flattened on white).", PERSON),
         ("eoir26a/signed-on-paper-<id>.pdf", "file", "The scan of the form the client signed on paper.", PERSON),
     ], "exported": True},
    34: {"id": "part14_explanations", "title": "The Part 14 explanations of the Yes answers", "area": "case", "files": ["part14_explanations.json"],
     "where": "data/clients/<case id>/part14_explanations.json", "format": "JSON object",
     "written_by": "The review app's Explain the Yes answers tab (src/part14_explain.py): an attorney's approval of an explanation, an approval taken back, a grammar "
                   "suggestion asked for or turned down. The explanations' text and the approvals themselves are review decisions (decisions.json, kind part14); this "
                   "file keeps what each approval was made over, so a change to the text, the voice or the facts is seen.",
     "version": 1, "versions": [(1, "The first and only version (brief L2, 10/04/2026). Added without raising it (10/04/2026, brief L3): picks and ranked, and library in an approval.")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("approvals", "object", "By the answer's fact key: the approval in force as it was made: item (the form's printed item), text, voice (client or office), facts "
                                 "(each blank's name and the value it had), wording (the firm's shipped wording it is, when not edited), edited, by, role, at, and library "
                                 "(what the firm's wording library did with the approved text: how (new, used, version or not_kept), id (the wording's), why).", PERSON),
         ("picks", "object", "By the answer's fact key: the firm's own wording a person picked for this case (src/wordings.py): wording (its id), text (as it was put in the explanation), "
                             "by, role, at. It is dropped when the explanation goes back to the suggestion.", PERSON),
         ("ranked", "object", "By the answer's fact key: the last time the local model was asked to put the firm's wordings in order (only when an attorney switched it on): candidates "
                              "(the wordings' ids), chosen (the id of the one it numbered, or empty), refused (why nothing was chosen), raw (what the model answered: a number), model "
                              "(its name), facts (what was true on the case), order and by (who asked, role, at).", PERSON),
         ("smoothing", "object", "By the answer's fact key: the last grammar suggestion: before, after, accepted (it passed the check), reason (why it was refused), "
                                 "engine (the local model's name), by (who asked, role, at), diff (word by word), same, and declined (who, role, at) when turned down.", PERSON),
         ("history", "list", "Approvals taken back: key, item, approval (as the card showed it), taken_back (who, role, at) and why.", PERSON),
     ], "exported": True},
    35: {"id": "questions", "title": "Questions asked about the case", "area": "case", "files": ["questions.jsonl"],
     "where": "data/clients/<case id>/questions.jsonl", "format": "JSON Lines",
     "written_by": "The review app, for every question asked in the case page's \"Ask about this case\" and every summary for the attorney (src/case_questions.py). "
                   "Appended only: nothing rewrites a line.", "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("id", "text", "The question's id: twelve hex digits (a summary's PDF is asked for by it).", ""),
         ("at", "text", "When it was asked (with its offset).", ""),
         ("who", "text", "Who asked: the signed-in staff member's name.", ""),
         ("role", "text", "Their role: attorney or paralegal (none when the app runs without staff accounts).", ""),
         ("kind", "text", "question, or summary (the summary for the attorney).", ""),
         ("question", "text", "The question in the person's own words, or \"Summary for the attorney\".", PERSON),
         ("outcome", "text", "How it ended: answered, not_in_record, unchosen (the model chose nothing usable: the record found is shown), "
                             "empty (the model answered nothing: the record found is shown), neutral (no record word and no lookup's shape: the record "
                             "found is shown), attorneys_call (a judgment: the record is shown, the model is not asked), english_only (asked in another "
                             "language with no word the product reads), unreachable (the local model could not be reached) or cut_off (its answer ran "
                             "too long).", ""),
         ("model", "text", "The local model's name, when it was asked.", ""),
         ("passages", "list", "Each passage of the case's record handed to the model: ref (which record it came from), says (what it says) and cite (where it "
                              "came from, in words).", PERSON),
         ("chosen", "list", "The passage numbers the model chose.", ""),
         ("raw", "text", "The model's own answer as it wrote it (never shown: only the numbers in it are used).", PERSON),
         ("answer", "object", "What staff were shown: lead, sentences (each a passage of the record in its own words, with where it came from), notes and refusal.", PERSON),
         ("parts", "list", "For a summary: each part (part, title, passages, answer), built from the record's passages without a model.", PERSON),
     ], "exported": True},
    36: {"id": "feedback", "title": "How the client said a step went", "area": "case", "files": ["feedback.jsonl"],
     "where": "data/clients/<case id>/feedback.jsonl", "format": "JSON Lines",
     "written_by": "The review app, the overnight run and the portal copy the client's answers onto the case from the portal's own folder, each once (src/client_case.py "
                   "sync_feedback). Appended only. Shown to the firm in Reports as counts per step and per office, with the sentences for those who may open the case; "
                   "never used for anything automatic.", "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("step", "text", "Which step the client was asked about: the milestone's id (agreement, documents, or mailed, biometrics, interview or decision with the filing or receipt and the day).", PERSON),
         ("kind", "text", "The kind of step: agreement, documents, mailed, biometrics, interview or decision.", ""),
         ("face", "text", "The face the client chose: good, ok or bad.", ""),
         ("comment", "text", "The optional sentence the client wrote (500 characters at most), in their own words.", PERSON),
         ("at", "text", "When they answered (with its offset).", ""),
         ("language", "text", "The language the client read the question in.", ""),
     ], "exported": True},
    37: {"id": "client_reminders", "title": "Reminders sent to the client about appointments", "area": "case", "files": ["client_reminders.json"],
     "where": "data/clients/<case id>/client_reminders.json", "format": "JSON object",
     "written_by": "The overnight run, when it reminds the client of a fingerprint appointment, an interview or a hearing the week before and the day before (src/client_reminders.py).",
     "version": 1, "versions": [(1, "The first and only version: one entry for each appointment and kind of reminder.")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("sent", "object", "Each reminder, by appointment, kind (week or day) and what it was for: the appointment's id (which holds a receipt number), then the kind.", PERSON),
         ("sent.<key>.kind", "text", "week (the week before) or day (the day before).", ""),
         ("sent.<key>.appointment", "text", "biometrics, interview or hearing.", ""),
         ("sent.<key>.for", "text", "The appointment's day (YYYY-MM-DD).", PERSON),
         ("sent.<key>.at", "text", "When the run tried it (with its offset).", ""),
         ("sent.<key>.status", "text", "sent, queued (waiting in the outbox: no provider), hand (protected case: the office reaches the client by hand), held, failed (a channel failed) or none (no channel the client agreed to).", ""),
         ("sent.<key>.channels", "object", "What each channel did: email, sms or whatsapp as sent, queued, skipped (no consent) or failed; all as hand or held. A channel that sent is never sent again; one that failed is tried again alone.", ""),
     ], "exported": True},
    38: {"id": "files", "title": "Files a case's work leaves", "area": "case",
     "files": ["*.pdf", "online_bundle_*.zip", "flag_report.txt", "rfe/*.pdf", "translations/*.pdf", "declarations/*.pdf", "source/*", "uploads/*"],
     "where": "data/clients/<case id>/", "format": "PDF, ZIP, JPEG, PNG, plain text",
     "written_by": "The reader and the review app: filled forms, packets, review bundles, letters, the flag report; scans the office or the client added.",
     "version": None, "versions": [], "fields": [
         ("*.pdf", "file", "A filled USCIS form, a packet, a review bundle, a letter or a response, as built (a draft until an attorney signs off).", PERSON),
         ("online_bundle_<filing>.zip", "file", "The files prepared for USCIS's online filing.", PERSON),
         ("flag_report.txt", "file", "The issues found for staff, as plain text.", PERSON),
         ("translations/translation-<document id>.pdf", "file", "A foreign-language document's translation with the translator's certificate, as made or signed.", PERSON),
         ("declarations/declaration-<filing>.pdf", "file", "The client's declaration as drafted from their own answers and as signed off.", PERSON),
         ("source/*, uploads/*", "file", "Scans and photos of the case's documents, as the pipeline read them.", PERSON),
     ], "exported": True},
    39: {"id": "case_assignment", "title": "Staff case responsibility and transfer history", "area": "case", "files": ["case_assignment.json"],
     "where": "data/clients/<case id>/case_assignment.json", "format": "JSON object",
     "written_by": "Authenticated active paralegals and attorneys through src/case_assignment.py under the existing case OS lock. Separate from access grants and task/deadline owners. Internal firm record, excluded from the attorney-selected client file.",
     "version": 1, "versions": [(1, "Current assignee and durable ordered revision/operation history with existing R2 ledger references.")],
     "fields": [
         ("version", "integer", "The schema version, currently 1.", ""),
         ("revision", "integer", "The monotonically increasing number of committed assignment actions; a stale revision cannot overwrite a later assignment.", ""),
         ("assignee", "object or null", "Current assigned staff identity {email, name, role}, or null. A historical snapshot, never current account or ACL authority.", PERSON),
         ("assignee.email", "text", "Existing normalized account email identity.", PERSON),
         ("assignee.name", "text", "Staff name snapshot at the assignment.", PERSON),
         ("assignee.role", "text", "Staff role snapshot at the assignment.", ""),
         ("history", "list", "Ordered durable transfer log; retained for idempotent retries and accountability, never silently trimmed.", PERSON),
         ("history[].revision", "integer", "Revision committed by this action.", ""),
         ("history[].operation", "text", "Random retry handle for this intentional action; a reused handle with a different canonical payload is rejected.", ""),
         ("history[].payload_sha256", "text", "SHA-256 of canonical normalized actor, action, target, optional reason and expected revision.", ""),
         ("history[].actor", "object", "Authenticated actor identity {email, name, role} recorded at the action; never accepted as current authority.", PERSON),
         ("history[].actor.email", "text", "The authenticated actor's normalized account identity.", PERSON),
         ("history[].actor.name", "text", "The actor's staff name when the action committed.", PERSON),
         ("history[].actor.role", "text", "The actor's current staff role when the action committed.", ""),
         ("history[].action", "text", "claim, reassign or explicit clear.", ""),
         ("history[].before", "object or null", "Prior staff identity {email, name, role}, or null when unassigned.", PERSON),
         ("history[].before.email", "text", "Prior owner's normalized account identity.", PERSON),
         ("history[].before.name", "text", "Prior owner's staff name snapshot.", PERSON),
         ("history[].before.role", "text", "Prior owner's staff role snapshot.", ""),
         ("history[].after", "object or null", "New staff identity {email, name, role}, or null for explicit clear.", PERSON),
         ("history[].after.email", "text", "New owner's normalized account identity.", PERSON),
         ("history[].after.name", "text", "New owner's current staff name at the action.", PERSON),
         ("history[].after.role", "text", "New owner's current staff role at the action.", ""),
         ("history[].reason", "text", "Optional staff explanation, at most 1,000 characters.", PERSON),
         ("history[].at", "text", "When the action committed, with its offset.", ""),
         ("history[].audit", "object", "state pending or recorded; a recorded marker adds the existing R2 row hash and timestamp. Reconciliation reference, not full chain/anchor verification.", ""),
         ("history[].audit.state", "text", "pending or recorded; pending remains explicit after a failed append or incomplete marker write.", ""),
         ("history[].audit.hash", "text", "Existing R2 row hash for a reconciled event, present only when recorded.", ""),
         ("history[].audit.at", "text", "Existing R2 event timestamp, present only when recorded.", ""),
     ], "exported": True},
    40: {"id": "caches", "title": "Caches the product rebuilds", "area": "case", "files": ["overview.json", "journey_summary.json", "confidentiality.json"],
     "where": "data/clients/<case id>/overview.json, journey_summary.json, confidentiality.json", "format": "JSON",
     "written_by": "The review app and the overnight run, to make lists fast (src/review/overview.py, src/restricted.py). Each holds a signature of the files it was built from "
                   "and is built again when one changes.", "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("overview.json", "object", "The case's row on All clients: its review counts and its summary (signature, row).", PERSON),
         ("journey_summary.json", "object", "The timeline's summary: track, stage, deadlines, open steps, next filings (signature, row).", ""),
         ("confidentiality.json", "object", "What the law says about the case (1367, 208.6 or none), kept until a file it was worked out from changes.", ""),
     ], "exported": False},
    78: {"id": "clio_sent", "title": "What went to Clio, for one case", "area": "case", "files": ["clio_sent.json"], "where": "data/clients/<case id>/clio_sent.json",
     "format": "JSON object",
     "written_by": "The Clio sync (src/connectors/clio.py sync_out, through src/connectors/clio_sent.py): nightly, and when someone presses Send now on the case page. Written only when it changes.",
     "version": 1, "versions": [(1, "The first and only version.")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("matter", "text", "The Clio matter's id.", ""),
         ("packet_at", "text", "When a filing packet or its review bundle last went to the matter (with its offset), or null.", ""),
         ("mailings", "integer", "How many mailing records have gone to the matter.", ""),
         ("stage_at", "text", "When the case's stage last went as a note, or null.", ""),
         ("end", "object", "Set when the case's end state went as a note: state, name, on (the day it ended), at, and reopened (when it was reopened afterwards).", ""),
         ("deadlines", "integer", "How many of the case's deadlines are open as calendar entries in Clio.", ""),
         ("tasks", "integer", "How many of the case's tasks are open as tasks in Clio.", ""),
         ("failed", "list", "What Clio refused in the last attempt, each with at and what (in words, with the retry); empty when the last attempt went through.", PERSON),
         ("by_hand", "object", "Who last pressed Send now for this case, and when: by and at.", ""),
     ], "exported": True},
}
