"""Firm records; keys retain the legacy global catalog order, not record versions.

Metadata is assembled once by registry; keep existing positions stable.
A newly appended record uses the next unused global position.
"""

from __future__ import annotations

from typing import Any

from .flags import PERSON, SECRET

RECORDS: dict[int, dict[str, Any]] = {
    0: {"id": "preview_scratch", "title": "Optional page-preview OCR scratch", "area": "firm", "files": ["preview-scratch/*/*"],
     "where": "data/preview-scratch/i485-preview-ocr-*/ temporary inputs/outputs", "format": "Temporary PNG/TSV",
     "written_by": "review.server optional bounded original-pixel lookup; app-owned no-link root supports WSL calling Windows Tesseract. TemporaryDirectory removes each operation; crash leftovers are disposable, never evidence.",
     "version": None, "versions": [(1, "Transient bounded preview scratch; no persisted record format or evidence authority.")], "fields": [("scratch", "file", "Temporary source-page rendering and OCR words, never authoritative original or approval.", PERSON)], "exported": False},
    1: {"id": "evaluation_authorizations", "title": "Optional case-scoped evaluation reference authorization", "area": "firm",
     "files": ["evaluation-authorizations/*/*.json"],
     "where": "Own firm data/evaluation-authorizations/<case>/", "format": "JSON object", "version": 1,
     "written_by": "Explicit retained own-firm attorney approval supplied for the optional CLI; evaluation_candidates validates and reads this authorization, rather than granting it automatically.",
     "versions": [(1, "Optional local reference authorization; never automatic training or independent adjudication. Own case namespace is removed by approved Q1 purge.")],
     "fields": [("version", "integer", "1.", ""), ("firm_root", "text", "Exact own installation root.", PERSON),
                ("corpus_root", "text", "Exact own source/example corpus root.", PERSON), ("cases", "array", "Exactly one authorized own case identifier.", PERSON),
                ("approved", "boolean", "Explicit retained attorney approval must be true.", ""), ("approved_by", "text", "Current active own-firm attorney email.", PERSON),
                ("approved_at", "timestamp", "Time of the retained explicit approval.", ""), ("purpose", "text", "evaluation; never automatic training permission.", ""),
                ("allowed_examples", "array", "Specific case/id/binding_sha256 entries authorized for reference export.", PERSON),
                ("example_bindings_sha256", "text", "Digest over the complete exact example bindings.", ""),
                ("approval_evidence", "object", "Own retained evidence file and sha256; local file evidence is not a signed attestation.", PERSON),
                ("revoked", "boolean", "Revoked approval cannot release references.", "")], "exported": True},
    2: {"id": "evaluation_authorization_evidence", "title": "Retained optional evaluation approval evidence", "area": "firm",
     "files": ["evaluation-authorizations/*/evidence/*.json"], "where": "Own firm data/evaluation-authorizations/<case>/evidence/", "format": "JSON object", "version": 1,
     "written_by": "Explicit retained own-firm approval supplied with the optional CLI authorization; evaluation_candidates validates it, without claiming a signed attestation.",
     "versions": [(1, "Case-scoped local approval evidence; removed with its own approved Q1 case namespace.")],
     "fields": [("version", "integer", "1.", ""), ("purpose", "text", "evaluation.", ""), ("approved", "boolean", "Explicit approval must be true.", ""),
                ("approved_by", "text", "Current active own-firm attorney email.", PERSON), ("approved_at", "timestamp", "Time of the explicit approval.", ""),
                ("authorization_sha256", "text", "Canonical digest binding the exact authorization.", "")], "exported": True},
    3: {"id": "evaluation_candidates", "title": "Optional evaluation candidate references", "area": "firm",
     "files": ["evaluation-candidates/*/*.json"], "where": "Own firm data/evaluation-candidates/<case>/", "format": "JSON object", "version": 1,
     "written_by": "evaluation_candidates local optional export after exact case-scoped attorney authorization and current source/example verification; no source PDFs or raw/final values are copied.",
     "versions": [(1, "References remain approved=false, independently_adjudicated=false and training_authorized=false. Own case namespace is removed by approved Q1 purge.")],
     "fields": [("version", "integer", "1.", ""), ("kind", "text", "evaluation_candidate_references.", ""),
                ("approved", "boolean", "False; references are not approved evaluation gold.", ""),
                ("independently_adjudicated", "boolean", "False; workflow observations do not become independent truth.", ""),
                ("training_authorized", "boolean", "False; reference export never grants training use.", ""),
                ("created_at", "timestamp", "Time this reference artifact was created.", ""), ("firm_root", "text", "Exact own installation root.", PERSON),
                ("actor", "object", "Current authorized own staff email and role.", PERSON), ("authorization_sha256", "text", "Digest of the exact case-scoped authorization.", ""),
                ("candidates", "array", "Own case, example_id, example_file, example_sha256, binding_sha256, source_provenance, reviewer(by/role/at), outcome and adjudication=pending; no raw or final values or source PDF copies.", PERSON),
                ("intervention", "object", "Descriptive workflow numerator/denominator/rate per stated unit; staff_seconds=null. No independent accuracy or labor claim.", PERSON),
                ("measurement", "object", "Framework and human_time_input with labor, wrong_person, false_split_merge and critical_field_error null until separately measured; explicit reason.", PERSON)], "exported": True},
    10: {"id": "communication_wording", "title": "Firm notice and actual wording-review evidence", "area": "firm", "files": ["communication_notice.json", "wording-evidence/*.json", "wording-evidence/*.pdf"],
     "where": "data/communication_notice.json and data/wording-evidence/<SHA256>.json|pdf", "format": "JSON object or immutable PDF", "version": None,
     "written_by": "Firm supplies versioned language notice; client_language_readiness reuses actual attorney rules approval and qualified-review maintenance history with retained bounded evidence.",
     "versions": [(1, "Actual rendered wording/default/office/template bundle binds review. Preserved on case purge and included in firm export/backup, never a client file release.")], "exported": True,
     "fields": [("schema_version", "integer", "Notice shape 1.", ""), ("version", "text", "Firm notice version.", ""), ("texts", "object", "Exact client-language notices; no shipped legal or language approval is fabricated.", ""),
                ("artifact", "object or PDF", "Actual attorney/qualified wording review evidence; immutable bounded bytes keyed by SHA256.", PERSON)]},
    11: {"id": "communication_stop", "title": "Verified STOP retry and retired replay identities", "area": "firm", "files": ["communication-stop/receipts/*.json", "communication-stop/queue.json", "communication-stop/destinations/*.json"],
     "where": "data/communication-stop, exact SID-derived receipt IDs and destination digest indexes", "format": "JSON object", "version": 1,
     "written_by": "portal.opt_out official SDK verified ingest and bounded installed worker retry; portal.communication_lifecycle Q1 cleanup under case then communication then ingest locks.",
     "versions": [(1, "Pending denies before cleanup. Explicit store/client members precede partial effects. Last proven destination cleanup retains only opaque retired ID to prevent replay; damaged inventory remains unresolved.")], "exported": False,
     "fields": [("version", "integer", "1.", ""), ("id", "text", "Opaque SHA256 of provider account/message identity; the only retained replay handle after retirement.", ""),
                ("state", "text", "pending, applied or retired.", ""), ("installation", "text", "Exact owning installation.", ""), ("retired_at", "timestamp", "Retired replay barrier time; retired shape has only version/id/state/installation/retired_at and no case, provider, destination or payload metadata.", ""),
                ("provider", "text", "twilio on active receipts only.", ""), ("account_sid", "text", "Verified configured provider account, active receipt only.", ""), ("message_sid", "text", "Verified message SID, active receipt only.", ""),
                ("channel", "text", "Verified sms or whatsapp sender/recipient channel.", ""), ("destination_sha256", "text", "Phone matching digest on active receipts and index filename; not anonymization.", PERSON),
                ("payload_sha256", "text", "Digest of verified complete form; no body retained.", ""), ("signature_sha256", "text", "Proof digest, no secret token retained.", ""), ("callback_sha256", "text", "Exact configured callback digest.", ""),
                ("members", "array", "Explicit store client/prospect plus own client ID and pending/applied/no_longer_matching state; Q1 preserves all other cases and main/prospect identity separation.", PERSON),
                ("received_at", "timestamp", "Verified receive time.", ""), ("effective_at", "timestamp", "Completed bounded revoke time.", ""), ("pending", "array", "Exact receipt IDs in shared FIFO queue or one destination denying index; never clear phone, body, secret or session.", "") ]},
    28: {"id": "prospects", "title": "First calls: people who are not clients yet", "area": "firm",
     "files": ["prospects/*/prospect.json", "prospects/*/answers.json", "prospects/*/office.json", "prospects/*/notes.json", "prospects/*/deadlines_set.json",
               "prospects/*/apply_for.json", "prospects/*/access.json", "prospects/*/engagement.json", "prospects/*/engagement/*.pdf"],
     "where": "data/prospects/<prospect id>/", "format": "JSON object, PDF",
     "written_by": "The review app: New prospect on All clients, then the prospect's own page (src/prospects.py). A person who has called and is not a client: in no list and no count "
                   "of clients. The folder also holds the prospect's notes (notes.json: the fields of a case's notes), tasks (deadlines_set.json: the fields of a case's deadlines, "
                   "each with task true), answers to what-could-apply-for (apply_for.json: the fields of a case's), restriction (access.json: the fields of a case's), office "
                   "(office.json: office, by, at) and, when the firm declined, the non-engagement letter (engagement.json and engagement/*.pdf: the fields of a case's).",
     "version": 1, "versions": [(1, "The first and only version (brief I4, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("id", "text", "The prospect's id: made from the name when the call was recorded; it can be a name.", PERSON),
         ("name", "text", "The person's name.", PERSON),
         ("phone", "text", "Their phone number.", PERSON),
         ("email", "text", "Their email address.", PERSON),
         ("language", "text", "The language they read the first questions in: pt, es, en or ht.", ""),
         ("office", "text", "The office the call was for, or null.", ""),
         ("how_heard", "text", "How they heard about the firm, as the person who took the call wrote it.", PERSON),
         ("called_on", "text", "The day of the call (YYYY-MM-DD).", ""),
         ("taken_by", "text", "Who took the call.", ""),
         ("kind", "text", "The kind of case when it is known (a track id, such as sij or vawa), or null. A kind the law protects restricts the prospect from the start.", ""),
         ("kind_name", "text", "That kind in words.", ""),
         ("consent", "object", "Whether the person agreed to be contacted by email, sms and whatsapp.", ""),
         ("created_by", "text", "Who recorded the call.", ""),
         ("created_at", "text", "When it was recorded (with its offset).", ""),
         ("questions_sent", "object", "Last actual provider-accepted first-question invitation: by, at and result. Later held/queued attempts preserve this success.", ""),
         ("questions_attempt", "object", "Latest first-question invitation attempt: by, at and actual sent/queued/held/none result. Does not advance the prospect stage without provider acceptance.", ""),
         ("waiting", "object", "Set when someone marked the prospect ready for the attorney: by, at.", ""),
         ("declined", "object", "Set when the firm declined: by, at, on (the day) and letter (the non-engagement letter's id).", ""),
         ("became_client", "object", "Set when the prospect became a client: id (the client's case id, which can be a name), by, at. Current explicit promotion adds its exact operation and immutable target_identity digest; legacy bare-ID association cannot claim a new promotion receipt.", PERSON),
         ("portal", "object", "A copy of the prospect's state in the portal: status, submitted_at, invited_at, last_invite and language.", ""),
         ("typed", "object", "The answers a person typed in from the call, by question: by, at and value. The prospect's own answers are not listed here.", PERSON),
         ("history", "list", "Everything done to the prospect, oldest first: at, by and what (in words, never a value).", ""),
         ("answers.json", "object", "A copy of what the portal holds of the prospect's answers to the first questions, by question id (the same shape as a client's answers).", PERSON),
         ("office.json", "object", "The office chosen: office, by, at.", ""),
     ], "exported": True},
    43: {"id": "drive_intake_groups", "title": "Selected Drive reservation groups", "area": "firm", "files": ["jobs/drive-receipts/????????????????????????????????????????????????????????????????.json"],
     "where": "data/jobs/drive-receipts/<operation SHA256>.json", "format": "JSON object",
     "written_by": "src/connectors/drive_intake.py enqueue; all local case associations precede submission. Q1 removes only the target members and retires group replay.",
     "version": 1, "versions": [(1, "Retained through ordinary job pruning until case cleanup; surviving members keep their reserved job IDs.")],
     "fields": [("version", "integer", "1.", ""), ("type", "text", "group.", ""), ("digest", "text", "SHA256 binding the full authorized preview; opaque retry barrier.", ""),
                ("state", "text", "reserving or reserved; never reader completion.", ""), ("retired", "boolean", "True after any member is purged; prevents group resubmission recreating a removed member.", ""),
                ("jobs", "object", "Remote folder ID to client (local case), id (reserved job ID or null before submission) and state; persisted before partial work.", PERSON)], "exported": False},
    44: {"id": "drive_intake_phases", "title": "Selected Drive copy and processing proofs", "area": "firm", "files": ["jobs/drive-receipts/????????????????????????????????????????????????????????????????-????????????????????????????????????????????????????????????????-phase.json"],
     "where": "data/jobs/drive-receipts/<operation SHA256>-<remote folder SHA256>-phase.json", "format": "JSON object",
     "written_by": "src/connectors/drive_intake.py execute; copy success is separate from reader completion. Q1 removes only the target case's proofs.",
     "version": 1, "versions": [(1, "Case association before copy.running; retained through ordinary job pruning until case cleanup.")],
     "fields": [("version", "integer", "1.", ""), ("type", "text", "phase.", ""), ("client", "text", "Existing authorized local case folder.", PERSON),
                ("remote_digest", "text", "SHA256 of the selected remote folder ID, matching the filename.", PERSON), ("digest", "text", "SHA256 of this case's exact preview.", ""),
                ("copy", "object", "running/completed, report (source, at, local case, remote ID, name, added/updated/skipped/gone filenames) and retained_sources (PDF filenames to SHA256).", PERSON),
                ("processing", "object", "not started/running/completed/held/failed; result has processing/review/EV holds, never signoff. Failure keeps exception type and copied_sources_retained.", PERSON)], "exported": False},
    45: {"id": "upload_job_operations", "title": "Job submission proofs", "area": "firm", "files": ["jobs/operation-*.json"],
     "where": "data/jobs/operation-<scope digest>.json", "format": "JSON object",
     "written_by": "src/jobs.py submit(operation_id=...); prevents a retried upload or selected Drive intake creating another immediate read job after completion or normal job cleanup.",
     "version": None, "versions": [(1, "Submission reservation retained until the case is purged; unavailable outcome requires follow-up, never invented success.")],
     "fields": [
         ("id", "text", "The one reserved job id.", ""),
         ("kind", "text", "The job kind.", ""),
         ("client", "text", "Authenticated client/case id; existing Q1 job purge removes proofs for this client.", PERSON),
         ("payload", "text", "Canonical SHA256 of the submitted job arguments; rejects changed payload under one operation id.", ""),
         ("state", "text", "Legacy upload proofs remain reserved and never recreate a missing job. New portal_process recovery proofs are reserved then published: a reserved job cannot execute, and only an unexecuted reservation may reconstruct its one job id. Published/pruned jobs remain unavailable.", ""),
         ("recovery_version", "integer", "Optional 1 for portal_process recoverable reservations; absent for existing upload proofs.", ""),
         ("created", "timestamp", "Optional stable job creation timestamp for a recoverable portal_process reservation.", ""),
     ], "exported": False},
    48: {"id": "accounts", "title": "Staff accounts", "area": "firm", "files": ["review_users.json"], "where": "data/review_users.json", "format": "JSON object",
     "written_by": "An attorney on Settings, Staff; the command line (src/review/auth.py, src/review/users.py). Written owner-only (0600).",
     "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("users", "object", "Every account, by email.", ""),
         ("users.<email>.name", "text", "The person's full name: it is recorded on every decision they make.", ""),
         ("users.<email>.role", "text", "attorney or paralegal; support for the provider's support person an attorney let in (Settings, Let support in: never given by the Staff section).", ""),
         ("users.<email>.active", "boolean", "False when the account is turned off.", ""),
         ("users.<email>.created_at", "text", "When the account was made (with its offset).", ""),
         ("users.<email>.salt, hash, scrypt", "text", "The password, stored only as a salted scrypt hash and the parameters it was made with.", SECRET),
         ("users.<email>.must_change", "boolean", "True while the one-time password has not been changed.", ""),
         ("users.<email>.failures, locked_until, lockouts, lock_minutes", "mixed", "Wrong tries in a row, when a lock ends, when locks happened, how long the last one was.", ""),
         ("users.<email>.totp", "object", "The authenticator app: its secret (encrypted), the last step used, when it was set up, and the recovery codes (hashed).", SECRET),
         ("users.<email>.devices", "object", "Computers remembered for 30 days, as hashes with their expiry.", SECRET),
         ("users.<email>.support", "object", "A support account's current session: its id, until when, the hours, plain or masked, the attorney who let support in and when, when support signed in, and when and by whom it ended (src/support.py). Its one-time code is the salt and hash above, removed once used.", ""),
         ("users.<email>.support_history", "list", "A support account's earlier sessions, the same shape (the last 20): Settings shows the last ten.", ""),
         ("sessions", "object", "Signed-in sessions, as hashes of their tokens, with their expiry.", SECRET),
     ], "exported": True},
    57: {"id": "secrets_log", "title": "The record of changes to keys and secrets", "area": "firm", "files": ["secrets_log.json"], "where": "data/secrets_log.json", "format": "JSON object",
     "written_by": "tools/rotate_secret.py (and the product when it moves a key out of deployment.json into the vault), and the review app when an attorney chooses how often a kind of key is changed "
                   "(Settings, Keys and secrets) (src/firmsecrets.py). Written owner-only (0600). It holds names, days and people, never a value or a fragment of one.",
     "version": None, "versions": [(1, "The only shape so far; no version field (brief R4, 10/04/2026).")],
     "fields": [
         ("cadence", "object", "How often each kind of key is changed, as the attorney chose: monthly, quarterly, yearly or not set (the kinds are listed on the Settings page).", ""),
         ("cadence.<kind>.cadence", "text", "monthly, quarterly, yearly or not set.", ""),
         ("cadence.<kind>.by", "text", "Who chose it.", ""),
         ("cadence.<kind>.at", "text", "When they chose it (with the offset). Counting starts from the later of this and the last change.", ""),
         ("changes", "list", "Every change to a key or secret, oldest first.", ""),
         ("changes[].name", "text", "Which secret, by its name (for example smtp.password).", ""),
         ("changes[].at", "text", "When (with the offset).", ""),
         ("changes[].by", "text", "Who: the person who ran the tool, or The product when it moved a key into the vault.", ""),
         ("changes[].how", "text", "set, rotated, recorded (the firm changed it in the environment and said so) or migrated (moved out of deployment.json).", ""),
     ], "exported": True},
    58: {"id": "calendar_feeds", "title": "Calendar addresses", "area": "firm", "files": ["calendar_feeds.json"], "where": "data/calendar_feeds.json", "format": "JSON object",
     "written_by": "The review app when a staff member makes a calendar address on Settings, My calendar (src/calendar_feed.py). Written owner-only (0600). The address itself is shown once "
                   "and never kept: only its SHA-256 is.",
     "version": 1, "versions": [(1, "The first and only version: one entry for each current calendar address.")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("feeds", "object", "Each current calendar address, by the SHA-256 of its secret token (the token cannot be read back).", SECRET),
         ("feeds.<hash>.email", "text", "The staff member the address is for.", ""),
         ("feeds.<hash>.kind", "text", "person (their own list) or firm (every case; an attorney's).", ""),
         ("feeds.<hash>.made_at", "text", "When the address was made (with its offset).", ""),
         ("feeds.<hash>.made_by", "text", "Who made it.", ""),
         ("feeds.<hash>.last_logged", "text", "The firm's day the address was last written to the staff access log: it is logged once a day, not at every poll (YYYY-MM-DD).", ""),
     ], "exported": False},
    59: {"id": "staff_reminders", "title": "Staff reminders", "area": "firm", "files": ["staff_reminders.json"], "where": "data/staff_reminders.json", "format": "JSON object",
     "written_by": "The review app when a staff member switches their own deadline reminders on or off (Settings, My calendar); the overnight run when it sends them (src/staff_reminders.py).",
     "version": 1, "versions": [(1, "The first and only version: each person's switch, and the reminders already sent.")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("consent", "object", "Each staff member's own choice, by their sign-in email. Off until they switch it on.", PERSON),
         ("consent.<email>.on", "boolean", "True when they want the e-mails.", ""),
         ("consent.<email>.at", "text", "When they last changed it (with its offset).", ""),
         ("sent", "object", "The e-mails already sent, so a second run the same night sends none again: person, kind (today or week) and the morning they were for, mapped to that morning's date.", PERSON),
     ], "exported": True},
    60: {"id": "upkeep", "title": "The upkeep log", "area": "firm", "files": ["maintenance_log.json"], "where": "data/maintenance_log.json", "format": "JSON object",
     "written_by": "The review app when someone marks an upkeep item checked on Keeping current (src/maintenance.py mark).", "version": None,
     "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("<item id>", "object", "One upkeep item the firm looks after (schemas/registers/maintenance.json).", ""),
         ("<item id>.last_checked", "text", "The date it was last checked (YYYY-MM-DD).", ""),
         ("<item id>.log", "list", "Every check: on (YYYY-MM-DD) and by (who).", ""),
     ], "exported": True},
    61: {"id": "settings", "title": "The firm's settings", "area": "firm", "files": ["settings.json"], "where": "data/settings.json", "format": "JSON object",
     "written_by": "An attorney on the Settings page (src/settings.py).", "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("<section id>", "object", "One Settings section (fees, Visa Bulletin month, poverty guidelines, the firm's details, sign-in, an office).", ""),
         ("<section id>.values", "object", "The values the firm set, by field.", ""),
         ("<section id>.updated_by", "text", "Who last changed the section.", ""),
         ("<section id>.updated_at", "text", "When (with its offset).", ""),
         ("<section id>.history", "list", "The earlier values, each with who and when (the last 20).", ""),
         ("_offices", "list", "The firm's other offices, as section ids, in the order they were added.", ""),
         ("_translators", "list", "The translators who may sign a certificate: id, name, languages, kind, competence, organization, address, added_by, added_at.", PERSON),
         ("_removed", "list", "Offices and translators taken off, with who and when.", ""),
     ], "exported": True},
    62: {"id": "firm_documents", "title": "The firm's letters to clients", "area": "firm", "files": ["firm_documents.json"], "where": "data/firm_documents.json",
     "format": "JSON object", "written_by": "An attorney on Settings, Firm documents (src/engagement.py save_document). The shipped wording is schemas/firm/firm_documents.json.",
     "version": 1, "versions": [(1, "The first and only version (brief I1, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("offices.<office id>.<kind>", "object", "One office's copy of one letter (engagement, non_engagement, disengagement, closing), as the firm edited it.", ""),
         ("offices.<office id>.<kind>.version", "integer", "Its version; english_version, the version its English last changed.", ""),
         ("offices.<office id>.<kind>.texts", "object", "Its paragraphs in each language (en, pt, es, ht), with words in square brackets the product fills in.", ""),
         ("offices.<office id>.<kind>.made_from", "object", "For each translation, the version of the English it was made from.", ""),
         ("offices.<office id>.<kind>.made_from_english", "object", "For each translation, the sha256 of the English it was made from: it is current while the English is the same.", ""),
         ("offices.<office id>.<kind>.by", "text", "Who edited it; at, when (with its offset).", ""),
         ("offices.<office id>.<kind>.history", "list", "The earlier versions, each with its texts, who and when.", ""),
     ], "exported": True},
    63: {"id": "destroyed", "title": "Files destroyed after their keeping date", "area": "firm", "files": ["destroyed.json"], "where": "data/destroyed.json",
     "format": "JSON object", "written_by": "An attorney on Keeping current, Files past their keeping date (src/engagement.py mark_destroyed). The product deletes nothing.",
     "version": 1, "versions": [(1, "The first and only version (brief I1, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("cases", "list", "One row per case recorded as destroyed, as below. It outlives the case's folder, so it keeps no name field; the case id itself can "
                            "be the client's name (a folder the front desk or an import named for the client).", ""),
         ("cases[].case", "text", "The case's id (the client's folder name, which can be a name).", PERSON),
         ("cases[].state", "text", "How the case had ended (declined, withdrawn, transferred, closed); state_name in words.", ""),
         ("cases[].ended_on", "text", "The day it ended (YYYY-MM-DD); until, its keeping date.", ""),
         ("cases[].file", "boolean", "Whether a file had been made to hand over.", ""),
         ("cases[].by", "text", "The attorney who recorded it; role; at, when (with its offset).", ""),
         ("cases[].folder_removed", "boolean", "The case's folder was removed from the clients folder.", ""),
         ("cases[].export_kept", "boolean", "An export of the case was kept.", ""),
         ("cases[].planning_only", "boolean", "Whether the office keeping period was a planning clock only; it grants no destruction authority.", ""),
         ("cases[].destruction_ready", "boolean", "Current case-specific legal destruction eligibility when the attorney recorded this row.", ""),
         ("cases[].policy_authority", "object", "The exact current require_destruction policy snapshot and approval proof retained when destruction was recorded.", PERSON),
         ("cases[].note", "text", "The attorney's note.", PERSON),
         ("cases[].examples_removed", "integer", "When the folder was removed: how many of the case's labelled examples (data/reader_examples/<case id>/) "
                                                 "were removed with it.", ""),
         ("cases[].evaluation_artifacts_removed", "object", "When folder_removed is true: own-case evaluation_authorizations and evaluation_candidates removed counts, recorded only after safe namespace cleanup succeeds. Other cases remain untouched.", ""),
     ], "exported": True},
    64: {"id": "retention", "title": "The offices' retention rules and the waiting period before a purge", "area": "firm", "files": ["retention.json"], "where": "data/retention.json",
     "format": "JSON object", "written_by": "An attorney on Settings, Keeping closed files (src/purge.py confirm_rule, set_wait).",
     "version": 1, "versions": [(1, "The first and only version (brief Q1, 10/05/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("offices.<office id>", "object", "The office's rule as the attorney confirmed it: years, from_majority (counted from the client's 18th birthday when that is later), "
                                          "state, by, role, at. The office's own years (office.retention_years) are saved with it; when they change, the rule is unconfirmed again.", ""),
         ("wait_days", "integer", "The days between asking for a purge and the purge (at least 7; 14 until set); wait_by and wait_at say who set it and when.", ""),
         ("history", "list", "Each earlier confirmation: office, before (the record it replaced), by, at.", ""),
     ], "exported": True},
    65: {"id": "purges", "title": "The cases purged, and the purges asked for or cancelled", "area": "firm", "files": ["purges.json"], "where": "data/purges.json",
     "format": "JSON object", "written_by": "An attorney on the case's Agreement and closing tab, and the purge job (src/purge.py). The firm's record that a case was purged: "
                                            "it keeps the case id and nothing else of the case.",
     "version": 1, "versions": [(1, "The first and only version (brief Q1, 10/05/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("cases.<case id>", "object", "The case's latest purge, as below. The case id itself can be the client's name, when the folder was named for the client.", PERSON),
         ("cases.<case id>.id", "text", "The purge's own id: the job that runs it names this, never the case.", ""),
         ("cases.<case id>.kind", "text", "The kind of case.", ""),
         ("cases.<case id>.state", "text", "waiting, cancelled or done.", ""),
         ("cases.<case id>.reason", "text", "The attorney's reason, with any name, number, date or address of the case masked out.", ""),
         ("cases.<case id>.early", "boolean", "Legacy early-request history is preserved. New requests are false and require current case-specific approval after the inclusive keeping date; a reason cannot bypass it.", ""),
         ("cases.<case id>.policy_authority", "object", "Exact current case-policy snapshot and destruction-approval digest retained at ask. Rechecked before confirmation, submission and first worker deletion alongside operational closure, waiting and second-attorney gates. Legacy/mismatched authority requires cancellation and renewed review. Interrupted deletion with missing identity/policy is an explicit incident hold, never authority to resume or delete a recreated same-ID case.", ""),
         ("cases.<case id>.asked_by, asked_at, purge_on", "text", "Who asked, when, and the day it runs (after the waiting period).", ""),
         ("cases.<case id>.needs_confirm, confirmed_by, confirmed_at", "mixed", "Whether a second attorney must confirm (the firm has more than one attorney account), who did and when.", ""),
         ("cases.<case id>.cancelled_by, cancelled_at", "text", "Who cancelled it and when.", ""),
         ("cases.<case id>.done_at, contact, originals, stores, left, copies", "mixed", "When it ran; the attempts to reach the client (how, the day, who); the originals "
                                                                                     "review in numbers; each store emptied with how many items; what could not be removed, "
                                                                                     "in words; the older backups and exports that may still hold the case.", ""),
     ], "exported": True},
    66: {"id": "originals_kept", "title": "The originals the office keeps after a purge", "area": "firm", "files": ["originals_kept.json"], "where": "data/originals_kept.json",
     "format": "JSON object", "written_by": "The purge job, from the attorney's review of the originals (src/purge.py run).",
     "version": 1, "versions": [(1, "The first and only version (brief Q1, 10/05/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("originals[]", "list", "One row per original kept: case (the case id), client (the client's name), kind (the kind of document), where (where it is stored), "
                                 "purged_on (YYYY-MM-DD). Nothing else of the case.", PERSON),
     ], "exported": True},
    67: {"id": "policies", "title": "Firm policies and rule approvals", "area": "firm", "files": ["policies_firm.json", "rules_approved.json"],
     "where": "data/policies_firm.json, data/rules_approved.json", "format": "JSON object",
     "written_by": "An attorney on Settings (src/rules/firm_policies.py) and on Keeping current (src/rules/approval.py).", "version": None,
     "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("policies_firm.json: edits", "object", "For each firm policy, every edit, oldest first: by, role, at, plain_text, set, enabled, the old values, hash, reverted.", ""),
         ("rules_approved.json: <rule id>", "list", "For each rule or policy, every approval: by, role, at, hash, plain_text, source.", ""),
     ], "exported": True},
    68: {"id": "wordings", "title": "The firm's wordings", "area": "firm", "files": ["wordings/*/*/*.json"], "where": "data/wordings/<form>/<answer>/<id>.json (I485_WORDINGS), owner-only",
     "format": "JSON, one file per wording",
     "written_by": "Learned from an attorney's approval of an explanation in Part 14 on a case (src/wordings.py, through src/part14_explain.py); read in from the firm's past filed forms by the "
                   "firm's IT person (tools/import_wordings.py) and approved in bulk by an attorney on Settings, Firm wordings; retired by an attorney. A wording is never deleted. "
                   "<form> is i485; <answer> is the answer the wording explains, or to_place for a past filing's text the product could not put on an answer.",
     "version": 1, "versions": [(1, "The first and only version (brief L3, 10/04/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("id", "text", "The wording's id: a hash of the form, edition, answer, voice and text, so two wordings that say the same are one.", ""),
         ("form", "text", "The form the wording is for (i485).", ""),
         ("edition", "text", "The edition of the form whose page, part and item numbers it was written under.", ""),
         ("key", "text", "The answer it explains (the product's own name for the box); empty for a text the product could not place.", ""),
         ("part", "text", "The part of the form the item is in, as that edition prints it.", ""),
         ("item", "text", "The item number, as that edition prints it.", ""),
         ("page", "text", "The page of the form the item is on, in that edition.", ""),
         ("voice", "text", "client (\"Yes, I ...\") or office (\"The applicant ...\"); empty when a past filing's voice could not be told.", ""),
         ("office", "text", "The office whose cases are offered it (the office's id).", ""),
         ("office_name", "text", "The same office's name.", ""),
         ("text", "text", "The wording itself, with a {slot} in place of every date, place, name and number of a case (and of the client's identifiers: names, A-Number, receipts, "
                          "date of birth, addresses, phone and e-mail). A person types nothing of a case into it: the product replaces it before it is kept.", ""),
         ("slots", "list", "Each slot in the text: its name, what it is in words, kind (fact: filled from a fact of the case; typed: written by a person each time; free: a date, place, "
                           "name or number no fact fills), and the fact keys it comes from.", ""),
         ("pattern", "object", "What was true on the case it was approved on: present (the facts true there) and absent (the facts it is chosen by that were not).", ""),
         ("status", "text", "approved, candidate (from a past filing, not yet approved), retired or discarded.", ""),
         ("origin", "text", "approval (approved on a case) or past_filing.", ""),
         ("created", "text", "When it was made (with its offset).", ""),
         ("approved", "object", "Who approved it (who, role) and when (at).", ""),
         ("parent", "text", "The id of the wording an edited approval started from (or an older edition's it was carried from), or empty.", ""),
         ("number", "integer", "Its version among the wordings it descends from: 1 for the first.", ""),
         ("uses", "list", "Each case it was used on: case (the case's id, which can be a client's name: shown only to people who may open the case), at, by, role, via (learned, offer or typed) "
                          "and withdrawn (who and when, when the approval on that case was taken back).", PERSON),
         ("uses[].case", "text", "The case's id.", PERSON),
         ("edits", "list", "The cases where a paralegal picked this wording and changed it before it was approved (case, at, by, became: the id of the new version; withdrawn: who and when, when the approval it led to was taken back).", PERSON),
         ("from_file", "text", "For a past filing's text: the name of the file it was read from, in the references folder (named for a case, so it can be a client's name).", PERSON),
         ("printed_as", "object", "For a past filing's text: the edition, part, item and page as that form printed them.", ""),
         ("placed_by", "text", "For a past filing's text placed on an answer of the current edition: how its item was found (the form's own numbers, or the table for its edition).", ""),
         ("retired", "object", "Who retired or set it aside, when and why.", ""),
         ("history", "list", "Every change: at, who, what.", ""),
     ], "exported": True},
    69: {"id": "reader_examples", "title": "The firm's reader examples", "area": "firm", "files": ["reader_examples/*/*.json"],
     "where": "data/reader_examples/<case id>/<id>.json (I485_READER_EXAMPLES), owner-only", "format": "JSON, one file per example",
     "written_by": "A by-product of work the office already does (brief M1, src/reader_examples.py): a confirm or a correction on a review card of a value a "
                   "reader read (src/review/state.py record_decision), and a box of the firm's hand-filled form that differs from a box a reader filled "
                   "(the monthly audit, src/audit_fill.py audit_forms). A decision taken back marks its examples undone. They hold a client's values: "
                   "case data under the same gate as the case, in the client's file handed over, and removed with the case's folder when an attorney "
                   "records it removed after its keeping date (src/engagement.py mark_destroyed). Nothing learns from them by itself.",
     "version": 1, "versions": [(1, "The first and only version (brief M1, 10/04/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("id", "text", "The example's id: a hash of the case, the decision (or the reference's box), the field, the document and the read.", ""),
         ("case", "text", "The case's id (the client's folder name, which can be a name); also the folder the example is in.", PERSON),
         ("doc_type", "text", "The kind of document the reader read (passport, i94, intake_questionnaire for the paper questionnaire's scan).", ""),
         ("field", "text", "The fact key the reader filled (applicant.date_of_birth).", ""),
         ("document", "text", "The document's name in the case (a file, or a part of one: name.pdf#p2-3).", PERSON),
         ("file", "text", "The file's name, without the part.", PERSON),
         ("page", "integer", "The page of the file the value was read from, counting from 1, when it is known; else empty.", ""),
         ("read_raw", "text", "The value exactly as the reader read it.", PERSON),
         ("read_normalized", "any", "The same value in the form the product compares (dates as YYYY-MM-DD, names in capitals).", PERSON),
         ("confidence", "number", "How sure the reader was, from 0 to 1.", ""),
         ("final_value", "any", "The value the office kept: the read value confirmed, the correction typed, or the box of the firm's hand-filled form.", PERSON),
         ("outcome", "text", "kept (the read value stood) or changed.", ""),
         ("how", "text", "confirm, correction (both on a review card) or hand_filled_form (the monthly audit).", ""),
         ("crop", "object", "Where the read sat on the page, when the OCR word boxes say so (the paper questionnaire's scan): page (from 1), box (left, top, "
                            "right, bottom in the page image's pixels), question and from; else empty.", ""),
         ("crop_note", "text", "When there is no crop, the sentence saying no word box is known for this read (a reader of the document's text).", ""),
         ("by", "text", "Who confirmed or corrected it (the decision's reviewer), or the firm's hand-filled form; role, the signed-in person's role.", PERSON),
         ("role", "text", "The signed-in person's role, when there was one.", ""),
         ("at", "text", "When the decision was made, or when the audit compared the form (with its offset).", ""),
         ("item", "text", "The review card's id (or reference:<form>:<box> for the audit), so a decision taken back finds its examples.", ""),
         ("undone", "object", "Set when the decision was taken back: by, role, at. An undone example is counted nowhere.", PERSON),
         ("software", "text", "The release that wrote it.", ""),
         ("observation", "object", "Workflow confirmation/correction/reference comparison with adjudication pending, training_authorized false, evaluation_reference false and staff_seconds null. Descriptive workflow labels are not independently adjudicated ground truth.", ""),
         ("source_provenance", "object", "state verified/legacy_unverified/stale/unavailable, reason, source_version, instance_id, retained source_sha256, evidence_fingerprint, boundary_fingerprint, at-read reader_manifest and canonical reader_manifest_sha256, original_range. Missing or stale bindings never receive inferred provenance.", PERSON),
         ("written", "text", "When the file was written (with its offset).", ""),
     ], "exported": True},
    70: {"id": "learning", "title": "The learning store", "area": "firm", "files": ["learning.db"], "where": "data/learning.db", "format": "SQLite database",
     "written_by": "The review app, from corrections staff approve (src/learning/).", "version": None, "versions": [(1, "A SQLite database with its own tables.")],
     "fields": [("learning.db", "file", "Corrections staff approved and the labels learned from them.", PERSON)], "exported": True},
    71: {"id": "overnight", "title": "The overnight run's records", "area": "firm",
     "files": ["batch_state.json", "batch_progress.json", "batch_log.jsonl", "batch_report.txt", "case_status_run.json", "case_status_usage.json", "accuracy_history.jsonl",
               "accuracy_latest.json"],
     "where": "data/batch_state.json, batch_progress.json, batch_log.jsonl, batch_report.txt, case_status_run.json, case_status_usage.json, accuracy_history.jsonl, accuracy_latest.json",
     "format": "JSON, JSON Lines, plain text", "written_by": "The overnight run (src/overnight.py, src/case_status.py, src/accuracy.py).", "version": None,
     "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("batch_state.json", "object", "For each case, how the last run went: status, when, the pipeline's version, why it ran, how long it took, its counts and any error.", PERSON),
         ("batch_progress.json", "object", "The current or last run: when it started and finished, how many cases, done, failed, running now, why it stopped.", PERSON),
         ("batch_log.jsonl", "lines", "One row a run: started_at, finished_at, version, done, failed, left, stopped.", ""),
         ("batch_report.txt", "file", "The morning report: what the run did, the cases with a blocking issue, the ones that could not be read.", PERSON),
         ("case_status_run.json, case_status_usage.json", "object", "Last night's USCIS case-status check and the day's use of its allowance.", ""),
         ("accuracy_history.jsonl, accuracy_latest.json", "mixed", "The nightly comparison of the pipeline's filled forms with hand-filled references: counts and figures by form and by cause, the counts of the last audit of what the office changes (audit), and the last full result.", PERSON),
     ], "exported": True},
    72: {"id": "audit_fill", "title": "The boxes the office changes", "area": "firm", "files": ["audit_fill.json", "audit_fill.partial.json"], "where": "data/audit_fill.json (I485_AUDIT_FILL), audit_fill.partial.json beside it", "format": "JSON object",
     "written_by": "The firm's own audit of its filled forms, run on its machine once a month (tools/fill_audit.py), and the overnight run, which counts the reviewers' Saves "
                   "every night (src/audit_fill.py). Owner-only, and never in the export of the firm's data: it holds the values of the boxes the office changed. While the "
                   "audit runs it keeps a checkpoint (audit_fill.partial.json, the same fields for the cases done so far) so a run that stopped can go on; it is dropped when "
                   "the audit finishes.",
     "version": 1, "versions": [(1, "The first and only version (brief K5, 10/03/2026).")],
     "fields": [
         ("version", "integer", "The record's version.", ""),
         ("software", "text", "The release that wrote it.", ""),
         ("forms", "object", "The last audit of the forms: at, day, cases, forms, boxes (compared), identical and changed, as counts; null before one has run.", ""),
         ("saves", "object", "The last counting of the reviewers' Saves: at, day, cases and saves, as counts; null before the first.", ""),
         ("skipped", "list", "What the last audit of the forms set aside and why, in words.", PERSON),
         ("rows", "list", "One row for each box a person changed on a case, as below.", ""),
         ("rows[].case", "text", "The case's id: the client's folder name, which can be a name.", PERSON),
         ("rows[].source", "text", "form (a filed or corrected form compared with the product's fill) or save (a value a person changed on a review card).", ""),
         ("rows[].form", "text", "The form's id (i485, n400 ...), or empty for an answer the forms are built from.", ""),
         ("rows[].ident", "text", "What makes two boxes the same box across cases: the fact behind the box, else the box's name.", ""),
         ("rows[].ref", "text", "The box's Part and Item in the form's own words.", ""),
         ("rows[].label", "text", "The question the box answers.", ""),
         ("rows[].kind", "text", "How the value changed: na_to_value, value_to_na, blank_to_value, value_to_blank, yes_to_no, no_to_yes or value_to_value.", ""),
         ("rows[].noun", "text", "What the box holds, in two words (a name, a city, a value).", ""),
         ("rows[].before", "text", "What the product filled in.", PERSON),
         ("rows[].after", "text", "What the office has: the hand-filled or corrected form's value, or what the person saved.", PERSON),
         ("rows[].basis", "text", "For a form: reference (filled by hand) or review (corrected on screen).", ""),
         ("rows[].reason", "text", "For a save: the reason the person gave.", PERSON),
         ("rows[].by", "text", "For a save: who saved it.", ""),
         ("rows[].at", "text", "For a save: when (with its offset).", ""),
     ], "exported": False},
    73: {"id": "inbox", "title": "The notice inbox", "area": "firm",
     "files": ["inbox/queue.json", "inbox/inbox_log.jsonl", "inbox/waiting/*", "inbox/not_ours/*", "inbox/originals/*"], "where": "data/inbox/",
     "format": "JSON, JSON Lines, PDF, JPEG, PNG", "written_by": "The notice inbox (src/inbox.py): scanned USCIS and court notices waiting for a person to place them, set aside as not the firm's, or the originals of ones already placed.",
     "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("queue.json", "list", "Each notice waiting: its file, the pages, what was read from it (form, receipt, names, A-Number), why it waits, the cases it might be.", PERSON),
         ("inbox_log.jsonl", "lines", "What the inbox did with each notice: routed, waiting, set aside; the case, how it was matched, who placed it.", PERSON),
         ("waiting/*, not_ours/*, originals/*", "file", "The scanned notices themselves, and for each set aside a record with the reviewer's note.", PERSON),
     ], "exported": True},
    74: {"id": "getting_started", "title": "Who has seen Getting started", "area": "firm", "files": ["getting_started.json"], "where": "data/getting_started.json", "format": "JSON object",
     "written_by": "The review app when an attorney presses \"I have seen it\" (src/getting_started.py).", "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [("seen", "object", "For each attorney's sign-in (email), when they saw the first-day page.", "")], "exported": True},
    75: {"id": "drive_settings", "title": "Installation-owned selected Drive settings", "area": "firm", "files": ["drive/settings.json"],
     "where": "data/drive/settings.json", "format": "JSON object", "written_by": "src/connectors/drive_settings.py: authorized attorney configuration and Q1 target-case cleanup. Shipped defaults never authorize mappings; no credentials are stored here.",
     "version": 1, "versions": [(1, "Typed provider configuration, bounded mapping, revision and retry/audit binding.")],
     "fields": [
         ("version", "integer", "The settings schema version.", ""),
         ("revision", "integer", "The settings revision used for compare-and-swap and current-worker validation.", ""),
         ("provider.root_folder_id", "text or null", "The explicitly configured Drive root id; no provider credential.", ""),
         ("provider.documents_subfolder", "text or null", "The configured documents subfolder name, or null for the selected folder itself.", ""),
         ("intake_mapping.version", "integer", "The mapping schema version.", ""),
         ("intake_mapping.revision", "integer", "The current settings revision; changed bindings invalidate old previews and queued work.", ""),
         ("intake_mapping.bindings", "object", "At most 2000 exact remote-folder ids mapped to existing local case ids; Q1 removes only the purged case's bindings.", PERSON),
         ("changed.actor", "text", "The authenticated attorney's account email, or system:purge for trusted retention cleanup; historical metadata grants no access.", PERSON),
         ("changed.name", "text", "The authenticated actor's display name or retention-cleanup label.", PERSON),
         ("changed.role", "text", "The existing authenticated event role, or system for unattended trusted cleanup; historical metadata grants no authority.", ""),
         ("changed.via", "text", "The existing event channel for the settings change or trusted cleanup.", ""),
         ("changed.at", "text", "When the current settings revision was written, with its offset.", ""),
         ("operation.id", "text", "The stable retry handle for the latest configuration operation only.", ""),
         ("operation.payload_sha256", "text", "The canonical actor, prior revision, provider and mapping digest binding this operation's retry.", ""),
         ("operation.previous_revision", "integer", "The revision before this change.", ""),
         ("operation.audit.state", "text", "Pending or recorded; ledger failure remains visible and retry repairs the marker without another revision.", ""),
         ("operation.audit.hash", "text", "When recorded, the reconciled R2 event hash; an event marker, not a signing certificate or daily-anchor assertion.", ""),
         ("operation.audit.at", "text", "When recorded, the R2 event's time with its offset.", ""),
     ], "exported": True},
    76: {"id": "clio", "title": "The Clio connection's state (without its secrets)", "area": "firm", "files": ["clio/state.json", "clio/settings.json"], "where": "data/clio/",
     "format": "JSON object", "written_by": "An attorney on Settings, Connections, and the nightly sync (src/connectors/clio.py). The vault of tokens and its key are never exported.",
     "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("settings.json", "object", "The mapping the firm chose (practice areas to questionnaires and offices, attorneys to offices, the calendar) with who set it and when.", PERSON),
         ("state.json", "object", "Who connected and when, the matters mapped to cases (with the client's name and matter number), what was sent out, the last sync and the recent problems.", PERSON),
     ], "exported": True},
    77: {"id": "clio_webhook", "title": "Clio's webhook subscriptions and the matters Clio said changed (without the signing secret)", "area": "firm", "files": ["clio/webhook.json", "clio/webhook_seen.log"],
     "where": "data/clio/webhook.json", "format": "JSON object",
     "written_by": "An attorney on Settings, Connections (Subscribe, Stop), Clio's own calls to the review app (src/connectors/clio_hooks.py), the hourly read and the overnight run's Clio step. "
                   "The signing secret is in the Clio vault, never here.",
     "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("hooks", "object", "Each subscription Clio made for the product, by Clio's id: model (document or matter), events, status (pending, enabled, suspended, expired), expires_at, made_by, made_at.", ""),
         ("pending", "object", "Set by Subscribe and kept for two minutes after it returns (or until every subscription has Clio's secret): until (a unix time) and by, the window in which Clio's first, unsigned call is taken.", ""),
         ("touched", "object", "The \"read tonight\" list: for each Clio matter Clio named, the case, since, last, n (how many messages) and kinds.", PERSON),
         ("lookups", "list", "Documents Clio named without saying their matter: looked up before the next read.", ""),
         ("webhook_seen.log", "lines", "One line for every message body taken in the last 31 days (pruned each night): its SHA-256 and the time, so a message sent again is recognised. The body itself is never kept.", ""),
         ("last_event", "text", "When Clio last sent a message that was taken (with its offset).", ""),
         ("last_read", "object", "The last read of the matters Clio named: at and line.", ""),
         ("problem", "object", "Why the subscription could not be renewed, when it could not: at and what.", ""),
     ], "exported": True},
    79: {"id": "sync_state", "title": "What the connectors mirrored", "area": "firm", "files": ["clients/sync_state.json"], "where": "clients/sync_state.json (configured document root, beside data/)", "format": "JSON object",
     "written_by": "The connectors' sync (src/connectors/sync.py).", "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [("clients", "object", "For each local mirrored client: the other system's id and name, optional source/provider binding, and for each document its file, fingerprint and name.", PERSON)], "exported": True},
    80: {"id": "reference", "title": "Hand-filled references and the official forms kept with them", "area": "firm", "files": ["reference/*"], "where": "data/reference/",
     "format": "PDF, JSON", "written_by": "The firm (its own hand-filled forms, which the accuracy comparison reads) and the product's official forms (src/accuracy.py).",
     "version": None, "versions": [], "fields": [
         ("reference/<case>.pdf, <case>.marks.json", "file", "A hand-filled form for a case and the boxes a person marked on it.", PERSON),
         ("reference/*", "file", "The official forms and the fee schedule the product keeps for itself.", ""),
     ], "exported": True},
}
