"""Portal records; keys retain the legacy global catalog order, not record versions.

Metadata is assembled once by registry; keep existing positions stable.
A newly appended record uses the next unused global position.
"""

from __future__ import annotations

from typing import Any

from .flags import PERSON, SECRET

RECORDS: dict[int, dict[str, Any]] = {
    4: {"id": "portal_promotion", "title": "Reciprocal prospect promotion and retirement", "area": "portal", "files": ["portal_promotion.json"],
     "where": "Own main/prospect portal client portal_promotion.json", "format": "JSON object", "version": 1,
     "written_by": "portal.promotion under the installation communication gate; source coordinator denies both identities before effects, with current staff authority over both canonical folders.",
     "versions": [(1, "Exact existing-pair promotion with original enrollment nonce identity, reciprocal completion and retained immutable receipt. No grant, verified control or document-subject transfer.")], "exported": True,
     "fields": [("version", "integer", "1.", ""), ("store", "text", "Exact canonical own portal store.", PERSON),
                ("client", "text", "Own client or prospect identity within its explicit store.", PERSON),
                ("role", "text", "source or target reciprocal ownership.", ""), ("state", "text", "pending or completed; incomplete reciprocal publication holds both identities.", ""),
                ("operation", "text", "Random exact operation identity, never a credential.", ""),
                ("source", "object", "Prospect kind/client and immutable identity digest over store, creation time and original enrollment nonce.", PERSON),
                ("target", "object", "Main client kind/client and immutable original enrollment identity digest.", PERSON),
                ("proposed", "object", "Exact normalized source email and phone snapshot; no permission or control grant.", PERSON),
                ("closure_on", "date", "Exact source closure date attributable only to this operation and reciprocal prospect association.", ""),
                ("started_at", "timestamp", "Recorded preparation time.", ""), ("plan_sha256", "text", "Canonical digest binding the immutable operation plan.", ""),
                ("new_target", "object", "Optional private new-target reservation: complete contact-empty unconsented immutable profile_snapshot and digest, fixed original enrollment_id, and the normal conflict search and decision. Source canonical plan precedes target mkdir or effects; current account/ACL and exact same-ID recovery are required.", PERSON),
                ("restriction_initialized", "boolean", "Optional attributed case-marker phase: initial new-target restriction preparation finished. Later missing restriction is held, never silently recreated or widened; current changed ACL remains authoritative.", ""),
                ("history", "array", "Named preparation, recovery and completion history retained without trimming.", PERSON)]},
    6: {"id": "portal_access", "title": "Contact-transition denial and recovery", "area": "portal", "files": ["portal_access.json"],
     "where": "Own main/prospect portal client portal_access.json", "format": "JSON object", "version": 1,
     "written_by": "portal.contact_transitions and portal.contact_control under the installation communication gate; coordinator precedes denial/profile effects; accepted redemption durably consumes the link before control receipt/session; recovery reloads current staff ACL.",
     "versions": [(1, "Existing contact changes, same-ID enrollment recovery and current email/phone control receipts. Phone neutral verification requires actual signoff before control; later substantive dispatch requires current proof. Pending coordinator holds all affected identities; grants are never silently revived. Destination control is not legal identity or consent.")], "exported": False,
     "fields": [("version", "integer", "1.", ""), ("store", "text", "Exact canonical main or prospect portal store.", PERSON), ("client", "text", "Own identity, distinct across stores even when IDs match.", PERSON),
                ("revision", "integer", "Monotonic contact-change fence; bound to current dispatch credentials.", ""), ("state", "text", "pending or ready. A referenced incomplete coordinator also denies access.", ""),
                ("history", "array", "Own immutable transition id/revision/action/channel/time history. Never silently trimmed; explicit size refusal.", PERSON),
                ("control_receipts", "array", "Retained verified destination control: version/state/id, own store/client/channel, explicit sign_in or verify_contact purpose, accepted attempt id and canonical SHA256, consumed credential SHA256, original enrollment digest, current consent/contact revisions, destination/group/wording digests and verified_at. Session references exact receipt; current consent, uniqueness, lifecycle and original nonce must still match. Accepted dispatch alone and consent-only manual links create no receipt. verify_contact sessions remain consent access only; regular phone sign_in requires prior current proof.", PERSON),
                ("pending", "object", "Temporary exact transition id and owner store-kind/client reference. Cleared only after complete coordinator publication and exact member revision check.", PERSON),
                ("transition", "object", "Temporary complete coordinator id/state/before-after digests, own immutable proposed email/phone snapshot and affected store-kind/client/channel/revoke/target-revision plan. New enrollment adds enrollment=true plus complete profile_snapshot and profile_sha256; recovery is exact same-ID under fresh own ACL. Removed only after all member cleanup, blocking dependent Q1 purge beforehand.", PERSON)]},
    7: {"id": "communication_consent", "title": "Actual client service-message permission", "area": "portal", "files": ["communication_consent.json"],
     "where": "data/portal/clients/<id>/communication_consent.json and the separate portal/prospects client subtree", "format": "JSON object",
     "written_by": "portal.communication_consent under the installation communication gate; current own principal or authorized staff records actual approval or denial, never imported flags or legal signatures.",
     "version": 1, "versions": [(1, "Exact current notice/destination/evidence and revision; denying revoke intent precedes credential cleanup. Q1 removes own subtree, Q2 never releases internal approvals.")], "exported": True,
     "fields": [("version", "integer", "1.", ""), ("client", "text", "Own client identity in the explicit main or prospect store.", PERSON),
                ("staff_preferences", "object", "Complete explicit staff-recorded channel snapshot: channels, note, recorded_at, actor, revision and evidence. Compare-and-swap requires the displayed revision; omitted grants are attributed revocations. Questionnaire access stays separate.", PERSON),
                ("store", "text", "Exact installation portal store path; distinguishes equal main/prospect IDs.", PERSON), ("revision", "integer", "Monotonic consent/contact denial revision.", ""),
                ("channels", "object", "Per-channel grant or revoke: state, revision, notice_version, language, destination_sha256, wording_sha256, actor/role, recorded_at, client_approved_at, method, source_kind, approval_description, immutable evidence and optional action_id/request_digest/principal_sha256/operation_id. Provider acceptance is separate.", PERSON),
                ("history", "array", "Authoritative immutable action attribution and proof bindings; historical staff turnover alone does not undo actual client signoff.", PERSON),
                ("questionnaire_access", "object", "Latest audited staff questionnaire handover evidence reference. Both current staff roles can prepare access after explicit client-request and recipient confirmation. Replacement invalidates earlier handover links and sessions; it creates no phone or email control proof.", PERSON),
                ("revocation_pending", "object", "Optional durable denying channel/requested_at/recorded_at/actor intent and verified STOP operation identity; remains denied after cleanup faults.", PERSON),
                ("revoked_effective_at", "timestamp", "When the denying revision and credential cleanup completed.", "") ]},
    8: {"id": "communication_evidence", "title": "Own client consent and request-language evidence", "area": "portal", "files": ["consent-evidence/*.json", "consent-evidence/*.pdf", "language-evidence/*.json", "language-evidence/*.pdf"],
     "where": "Each main/prospect portal client consent-evidence or language-evidence folder, named by SHA256", "format": "Bounded immutable JSON object or PDF", "version": None,
     "written_by": "portal.communication_consent retains only own bounded evidence under current authorization; actual client HTTP creates server-timed explicit signoff proof.",
     "versions": [(1, "References have kind, sha256 and format only; no arbitrary path or URL. Q1 removes own subtree; client release excludes internal proof even if misregistered.")], "exported": True,
     "fields": [("artifact", "object or PDF", "Actual retained bytes, maximum 4 MiB. Client signoff JSON holds scope/client/store/channel/destination and wording digests, language/notice, agree/name/action identity, server time/principal digest/bootstrap attribution and email_control false for consent-only access; contains no cookie/token.", PERSON)]},
    9: {"id": "communication_dispatch", "title": "Provider acceptance before credential activation", "area": "portal", "files": ["communication-attempts/*.json"],
     "where": "Own main/prospect portal client communication-attempts/<32hex>.json", "format": "JSON object", "version": 1,
     "written_by": "portal.communication_consent dispatch; the gate covers eligibility, pending proof/token, bounded provider call and durable result.",
     "versions": [(1, "Pending never authenticates; accepted requires actual sent result and complete sane timestamps/current bindings. Q1 removes own subtree; excluded from firm export and client release.")], "exported": False,
     "fields": [("version", "integer", "1.", ""), ("id", "text", "Random 32hex attempt identity, not the credential.", ""), ("client", "text", "Own current client ID.", PERSON),
                ("store", "text", "Current explicit portal store.", PERSON), ("channel", "text", "email, sms or whatsapp. Phone sends require actual signoff, unique full destination, reviewed wording and current control, except the explicit neutral verify_contact bootstrap; built-in provider requires exact authenticated STOP settings.", ""),
                ("revision", "integer", "Current grant revision.", ""), ("destination_sha256", "text", "Bound matching destination digest, not anonymization.", PERSON),
                ("contact_revision", "integer", "Current own contact-transition revision; old or unbound credentials refuse.", ""),
                ("contact_group_sha256", "text", "Exact per-destination normalized identity group digest; unrelated enrollments do not invalidate it.", PERSON),
                ("enrollment_sha256", "text", "Own original enrollment nonce/store/client/creation digest. Same-ID recreation cannot reuse the credential or receipt.", PERSON),
                ("purpose", "text", "sign_in for full credentials, notification without a credential, or protected neutral verify_contact before phone proof. Purpose remains exact through acceptance and redemption; notifications cannot establish control, and verification sessions cannot access questionnaire, messages, uploads or closed records.", ""),
                ("wording_sha256", "text", "Exact reviewed bundle digest.", ""), ("state", "text", "pending, accepted or unaccepted; acceptance is not delivery.", ""),
                ("created_at", "timestamp", "Before provider call.", ""), ("recorded_at", "timestamp", "Durable provider-result timestamp.", ""), ("provider_status", "text", "sent, failed, dry-run, queued or unknown; only sent can activate a current credential.", "") ]},
    41: {"id": "portal", "title": "The client portal's records", "area": "portal",
     "files": ["profile.json", "answers.json", "uploads.json", "tasks.json", "requests.json", "messages.json", "skipped_tasks.json", "journey.json", "engagement.json",
               "feedback.json", "fee_waiver.json", "fee_waiver/*", "events.jsonl", "uploads/*.pdf", "capture-evidence/*.image"],
     "where": "data/portal/clients/<client id>/", "format": "JSON, JSON Lines, PDF",
     "written_by": "The portal when the client answers or uploads, the review app when staff ask or reply, the overnight run for the client's list (src/portal/store.py).",
     "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("profile.json", "object", "The client: id (their case id, which can be a name), name, phone, email, language, consent (email, sms, whatsapp), status, created_at, filing, office, invited_at, "
                                    "last_invite, last_reminder_at, submitted_at, added_by, added_at, source, prospect (the id of the first call a client began as); name_history retains prior/changed-to names, who/role/at and confirmed subject_id/revision. Name corrections preserve stable id and all access/consent links.", PERSON),
         ("answers.json", "object", "The client's questionnaire answers, by question (and, once the office sends it, the fee waiver request's nine monthly lines, each as dollars and cents).", PERSON),
         ("uploads.json", "list", "Each upload: id, doc_id (what was asked for), filename, stored, size, sha256 (stored PDF), source_sha256 (original upload bytes), uploaded_at, status, retake, source, reading; optional capture carries version, policy, source_dimensions, corners, selection, client_reported_quality, quality_review_required, original_sha256, derivative_sha256, derivative_dimensions, transform, original_stored, derivative_stored. Camera geometry/quality are untrusted client reports; server hashes bind immutable original and auxiliary crop. The original PDF is pipeline evidence; a corrected image never replaces it.", PERSON),
         ("capture-evidence/*.image", "file", "Immutable original JPG/PNG capture bytes and optional linked corrected/cropped auxiliary image. Original and derivative hashes, dimensions and client-reported transformation are retained in uploads.json. Partial .part writes are excluded from export.", PERSON),
         ("tasks.json", "list", "What the client still has to answer or upload, and the office's confirm tasks, which quote the values to confirm (a Social Security number among them); an info task with office_has set closes the request for a paper the office recorded the client has none of; the worker rebuilds it.", PERSON),
         ("requests.json", "list", "Questions and requests the office sent: id, text, doc_id, by, asked_at, status, the client's reply or upload, delivery, settled_at; closed_at, closed_by and closed_by_absence when the office recorded that the client has no such paper and closed the request. Actual custom wording review is language_review with exact content/bundle/language digest, mode as_written/translated/english_fallback, current actor attribution, retained own evidence, qualification or deliberate fallback reason; language_history preserves actions. Current computed language_hold withholds unreviewed drafts without losing content. Internal review metadata is excluded from client file release.", PERSON),
         ("messages.json", "list", "The client's messages to the office and the office's answers: id, from, text, at, by, status, handled_by, handled_at, seen_at.", PERSON),
         ("skipped_tasks.json", "list", "Items left off the client's list because the office had decided them already.", ""),
         ("journey.json", "object", "The case's stage in plain language for the client, per language: what happens now and next, USCIS's own status line for each receipt as USCIS gave it (English), "
                                    "the appointments with their preparation sheets, and the steps done (for \"how was this step\").", ""),
         ("feedback.json", "list", "The client's answers to \"how was this step\": step, kind, face (good, ok or bad), comment (their optional sentence), at, language. Copied onto the case as feedback.jsonl.", PERSON),
         ("engagement.json", "object", "The agreement on the client's page (letter: id, kind, titles, texts, language, date, translation, approved consent); the signature retains the exact shown letter_snapshot and consent. Neutral file_sent boolean contains no link or bundle contents. The client's signature "
                                       "(signed: letter, how, typed_name, at, address, language) and the case's end (ended: state, since, letter). "
                                       "profile.json's declined_on stops the client's links from that day (src/engagement.py).", PERSON),
         ("fee_waiver.json", "object", "The fee waiver request on the client's page: request (id, at), signing (opened_at, drawn, figures: the nine amounts to sign, name: the client's legal name the case held, and sentence: item 4 in English "
                                       "and, when it is a shipped wording, in each language), viewed (when the client first opened it), name_refused (request, at: each time another name was typed; "
                                       "the name itself is not kept) and signed (request, how, typed_name, case_name, at, address, "
                                       "language, covers, drawn: file and sha256). The client's amounts themselves are in answers.json (src/eoir26a.py).", PERSON),
         ("fee_waiver/*", "file", "The signature the client drew on their phone (a small PNG).", PERSON),
         ("events.jsonl", "lines", "The portal's own log for this client: at, event (sign-ins, answers saved, uploads, requests), and details such as by or the question ids; effect is a payload-free digest used to reconcile a retried upload audit event.", ""),
         ("uploads/*.pdf", "file", "The documents the client uploaded (photos were turned into PDFs on upload).", PERSON),
     ], "exported": True},
    42: {"id": "upload_receipts", "title": "Upload recovery receipts", "area": "portal", "files": ["upload-receipts/*.json"],
     "where": "data/portal/clients/<client id>/upload-receipts/<attempt digest>.json", "format": "JSON object",
     "written_by": "The client portal (src/portal/upload_recovery.py): stages a payload-bound upload and reconciles its file, records, audit and queue effects.",
     "version": 1, "versions": [(1, "Durable retry receipt; original source hash is separate from the stored converted PDF hash.")],
     "fields": [
         ("version", "integer", "Receipt schema version, 1.", ""),
         ("key", "text", "SHA256 of the opaque browser attempt token; scoped by the authenticated client folder, not document identity.", ""),
         ("source_sha256", "text", "SHA256 of the original uploaded bytes, before image conversion.", ""),
         ("capture_binding", "text or null", "Canonical SHA256 binding capture metadata for retry identity; linked immutable original/derivative filenames reside in record.capture.", ""),
         ("record", "object", "The immutable planned upload row: id, doc_id, filename, stored, size, sha256, source_sha256, uploaded_at, status and optional retake. Stored hash identifies the converted PDF; source hash identifies original bytes.", PERSON),
         ("requests", "list", "Each targeted open request: id and SHA256 fingerprint of the full original request. A replacement under the same id is not answered by this attempt.", ""),
         ("retakes", "list", "Each targeted unanswered retake: id and SHA256 fingerprint of the full original task. A rebuilt task under the same id is not marked received by this attempt.", ""),
         ("status", "text", "pending before commit, incomplete if follow-up cannot be reconciled, complete after reconciliation. Receipt completion never asserts that the document reader succeeded.", ""),
         ("queued", "boolean", "The keyed overnight queue effect was written.", ""),
         ("reading", "text or null", "now, tonight or unavailable: immediate job outcome unavailable never causes duplicate submission.", ""),
     ], "exported": True},
    46: {"id": "portal_processing_receipts", "title": "Portal intake processing receipts", "area": "portal",
     "files": ["processing-receipts/*.json", "processing-receipts/*.tmp"], "where": "data/portal/clients/<client id>/processing-receipts/<generation>.json",
     "format": "JSON object", "written_by": "src/portal/queue_bridge.py; durable internal processing and conditional generation acknowledgment.",
     "version": 1, "versions": [(1, "Bounded attempts with explicit completion/acknowledgment; interrupted pipeline effects may replay.")],
     "fields": [
         ("version", "integer", "Receipt schema version, 1.", ""),
         ("identity", "object", "Client id, generation, explicit clients_root/portal_root/jobs_root and use_policies; canonical operation scope.", PERSON),
         ("created", "timestamp", "When the generation receipt was created.", ""),
         ("state", "text", "pending, processing, failed, processed, acked or superseded; processing completion is separate from queue acknowledgment.", ""),
         ("attempts", "list", "At most three attempts: canonical operation digest, created timestamp, published job id and optional finite retry_at epoch seconds.", ""),
         ("processing_at", "timestamp", "When this attempt began processing.", ""),
         ("processed_at", "timestamp", "When a valid complete pipeline output was observed and durably recorded.", ""),
         ("input_snapshot_before", "text", "Canonical digest of portal metadata-file hashes before work; not an atomic snapshot.", ""),
         ("input_snapshot_after", "text", "Canonical digest of portal metadata-file hashes after work.", ""),
         ("input_changed_during_processing", "boolean", "Metadata snapshot digests differed.", ""),
         ("queue_generation_after", "text or null", "Generation observed after processing.", ""),
         ("newer_generation_observed", "boolean", "A different generation was observed and retained.", ""),
         ("outcome", "object", "Completed task count and blocking/review/informational counts; no message or answer values.", ""),
         ("acknowledgment", "text", "acknowledged, absent or newer_generation_retained.", ""),
         ("acknowledged_at", "timestamp", "When conditional queue acknowledgment was durably recorded.", ""),
         ("last_job_state", "text", "State observed when an attempt could not prove complete processing.", ""),
         ("replay_possible", "boolean", "A later bounded attempt may replay pipeline effects after interruption.", ""),
         ("superseded_at", "timestamp", "When work skipped an already replaced/absent queued generation.", ""),
     ], "exported": False},
    47: {"id": "portal_secrets", "title": "The portal's sign-in table and outbox", "area": "portal", "files": ["auth.json", "outbox.jsonl", "queue/*"],
     "where": "data/portal/auth.json, outbox.jsonl, queue/", "format": "JSON, JSON Lines",
     "written_by": "The portal (src/portal/store.py, src/portal/notify.py).", "version": None, "versions": [(1, "The only shape so far; no version field.")],
     "fields": [
         ("auth.json", "object", "Sign-in links and sessions keyed by SHA256 with expiry, explicit sign_in, verify_contact, consent_only or staff_questionnaire purpose. Provider access binds accepted dispatch/current consent/contact/original enrollment. Staff questionnaire handover binds current authorized staff, retained own-client confirmation evidence, current recipient contacts and subsequent revocation, without provider delivery or contact-control proof. Reading-language changes retain staff handovers; questionnaire_binding_version=2 binds id/email/phone without language, and legacy handovers accept supported reading languages with the same recipient. Full sign-in sessions reference a durably retained verified control_receipt; one-use link removal precedes proof/session. verify_contact remains own consent access, never general or closed access. Manual consent_only never verifies control.", SECRET),
         ("outbox.jsonl", "lines", "Messages waiting to be sent: they can hold working sign-in links.", SECRET),
         ("queue/<client id>", "file", "A client waiting to be processed: version 1 generation token and at timestamp; legacy timestamp-only markers remain readable. Conditional acknowledgment retains newer generations.", ""),
     ], "exported": False},
}
