"""Field-by-field comparison of a pipeline-filled I-485 against a
reference I-485 a paralegal filled by hand for the same client.

The reference is used *only* here, after the fact, as a scoring key --
never as a pipeline input (docs/decisions.md: the past filled I-485 must
not feed the fill). Its value is in the gaps: every field the paralegal
filled that the pipeline didn't is either a missing extractor, a
handwritten questionnaire field, a firm policy default, or a mistake on
one side, and knowing which is what says what to automate next.

Fields are matched by their short name (form1[0].#subform[N]. prefix
stripped) because the reference may be an older form edition whose
subform numbering differs -- confirmed on the real example, where the
01/20/25 and 09/18/26 editions share 762 of their short names.

Usage: python src/compare.py REFERENCE.pdf OURS.pdf [--csv out.csv]
"""

from __future__ import annotations

import csv
import re
import sys
from dataclasses import dataclass
from pathlib import Path

_PREFIX = re.compile(r"^form1\[0\]\.#?subform\[\d+\]\.")


_OLD_HEADER_A_NUMBER = re.compile(r"^AlienNumber\[(\d+)\]$")


def short_name(full_name: str) -> str:
    name = _PREFIX.sub("", full_name)
    # 01/20/25 edition names the page-header A-number copies AlienNumber[0..23];
    # 09/18/26 names them Pt1Line4_AlienNumber[1..24].
    header = _OLD_HEADER_A_NUMBER.match(name)
    if header:
        return f"Pt1Line4_AlienNumber[{int(header.group(1)) + 1}]"
    return name


@dataclass
class FieldComparison:
    short_name: str
    description: str
    reference: str
    ours: str

    @property
    def status(self) -> str:
        if not self.reference and not self.ours:
            return "both_blank"
        if not self.ours:
            return "missing"
        if not self.reference:
            return "extra"
        return "match" if normalize(self.reference) == normalize(self.ours) else "mismatch"


def normalize(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip().upper()


def _value(field: dict) -> str:
    v = field.get("/V")
    if v is None or v == "/Off":
        return ""
    return str(v).strip()


_WIDGET_INDEX = re.compile(r"\[\d+\]$")

# Generated by the form itself (edition/page stamp), not entered data.
_IGNORED = re.compile(r"PDF417BarCode")


def read_fields(pdf_path: str | Path, prefix: str = "", exclude: tuple[str, ...] = (), reader=None) -> dict[str, tuple[str, str]]:
    """short name -> (value, tooltip). Where one short name repeats across
    subforms, the first non-blank value wins.

    Checkbox/radio widgets (value like "/Y", "/BN") are grouped under
    their name without the trailing [n], valued by the set of selected
    on-values: widget order within a question differs between form
    editions (on the real example, Eye Color's [2] is a different option
    in the 01/20/25 edition than in 09/18/26), but on-values don't.

    A packet holds several forms in one PDF, each form's fields renamed with the form's id in front (src/packet.py _own_fields): prefix reads one
    of them (its fields, with the prefix taken off); exclude leaves out the fields of the forms that have one (the I-485, which keeps its own
    names). reader: an open PdfReader, so one file read for several forms."""
    from pypdf import PdfReader

    if reader is None:
        reader = PdfReader(str(pdf_path))
        if reader.is_encrypted:
            reader.decrypt("")
    out: dict[str, tuple[str, str]] = {}
    choices: dict[str, set[str]] = {}
    choice_tips: dict[str, str] = {}
    for full, field in (reader.get_fields() or {}).items():
        if _IGNORED.search(full) or (prefix and not full.startswith(prefix)) or (exclude and full.startswith(exclude)):
            continue
        full = full[len(prefix):]
        name = short_name(full)
        value = _value(field)
        tooltip = str(field.get("/TU") or "")
        if field.get("/FT") == "/Btn":
            group = _WIDGET_INDEX.sub("", name)
            choices.setdefault(group, set())
            if value:
                choices[group].add(value)
            choice_tips.setdefault(group, re.sub(r"\s*Select [^.]*\.\s*$", "", tooltip))
            continue
        if name not in out or (value and not out[name][0]):
            out[name] = (value, tooltip)
    for group, selected in choices.items():
        out[group] = (" ".join(sorted(selected)), choice_tips[group])
    return out


def compare(reference_pdf: str | Path, ours_pdf: str | Path) -> list[FieldComparison]:
    reference = read_fields(reference_pdf)
    ours = read_fields(ours_pdf)
    rows = []
    for name in sorted(set(reference) | set(ours)):
        ref_value, ref_tip = reference.get(name, ("", ""))
        our_value, our_tip = ours.get(name, ("", ""))
        rows.append(FieldComparison(name, our_tip or ref_tip, ref_value, our_value))
    return rows


def summarize(rows: list[FieldComparison]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row.status] = counts.get(row.status, 0) + 1
    return counts


def main(argv: list[str]) -> None:
    reference_pdf, ours_pdf = argv[0], argv[1]
    rows = [r for r in compare(reference_pdf, ours_pdf) if r.status != "both_blank"]
    print(summarize(rows))
    if "--csv" in argv:
        out = Path(argv[argv.index("--csv") + 1])
        with out.open("w", newline="", encoding="utf-8") as fh:
            writer = csv.writer(fh)
            writer.writerow(["status", "field", "reference", "ours", "description"])
            for r in rows:
                writer.writerow([r.status, r.short_name, r.reference, r.ours, r.description])


if __name__ == "__main__":
    main(sys.argv[1:])
